package test-components:interfaces;

world component {
  import wasi:sockets/instance-network@0.2.2;
  import wasi:sockets/tcp-create-socket@0.2.2;
  import wasi:sockets/tcp@0.2.2;
  import wasi:sockets/udp-create-socket@0.2.2;
  import wasi:sockets/udp@0.2.2;

  // legacy imports
  import wasi:config/runtime@0.2.0-draft;

  import test-components:testing/busybox@0.1.0;
  import test-components:testing/pingpong@0.1.0;

  export wasi:http/incoming-handler@0.2.2;
  export wasmcloud:messaging/handler@0.2.0;
  export wasmcloud:messaging/incoming-handler@0.3.0;
}
