package test-components:ponger-config;

world component {
  export test-components:testing/pingpong@0.1.0;
  import wasmcloud:secrets/store@0.1.0-draft;
  import wasmcloud:secrets/reveal@0.1.0-draft;
}
