name: "Rust: Setup"
description: This action installs Rust tools
inputs:
  rust-toolchain:
    description: "Rust toolchain"
    required: false
    default: "stable"
  rust-targets:
    description: "Comma separated list of additional targets"
    required: false
    default: "wasm32-wasip1,wasm32-wasip2"
  rust-components:
    description: "Comma separated list of additional components"
    required: false
    default: "clippy, rustfmt"
  install-zigbuild:
    description: "Install Zig compiler"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    # Rust Setup
    - name: Install Rust
      uses: dtolnay/rust-toolchain@56f84321dbccf38fb67ce29ab63e4754056677e0 # master
      with:
        toolchain: ${{ inputs.rust-toolchain }}
        targets: ${{ inputs.rust-targets }}
        # rust-src is required when using cargo-zigbuild for cross-compilation
        components: ${{ inputs.install-zigbuild == 'true' && format('{0}, rust-src', inputs.rust-components) || inputs.rust-components }}
    - uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6 # v2.7.8
    - name: Install Zig for zigbuild
      if: ${{ inputs.install-zigbuild == 'true' }}
      uses: mlugg/setup-zig@aa9ad5c14eb3452e235a441c4f9a8e89f20d97bd # v2.0.0
      with:
        version: 0.13.0
    - name: Install cargo zigbuild
      if: ${{ inputs.install-zigbuild == 'true' }}
      uses: taiki-e/install-action@86c23eed46c17b80677df6d8151545ce3e236c61 # v2.50.7
      with:
        tool: cargo-zigbuild
