apiVersion: v1
kind: Service
metadata:
  name: wasi3-ai-app
  namespace: wasmcloud
spec:
  type: LoadBalancer
  selector:
    wasmcloud.com/hostgroup: default
    wasmcloud.com/name: hostgroup
  ports:
    - port: 80
      protocol: TCP
      nodePort: 30950
---
apiVersion: runtime.wasmcloud.dev/v1alpha1
kind: WorkloadDeployment
metadata:
  name: wasi3-ai-app
spec:
  replicas: 1
  template:
    spec:
      hostSelector:
        hostgroup: default
      volumes:
        - name: wasmcloud-data
          hostPath:
            path: /var/data # should match path in host deployment        
      kubernetes:
        service:
          name: wasi3-ai-app
      components:
        - name: wasi3-ai-app
          image: ghcr.io/bharattech/wasi-ai-app-web:0.2.0
          localResources:
            volumeMounts:
              - name: wasmcloud-data
                mountPath: /data # where data is mounted inside component
        - name: wasi-ai-app-transcriber
          image: ghcr.io/bharattech/wasi-ai-app-transcriber:0.2.0
          localResources:
            volumeMounts:
              - name: wasmcloud-data
                mountPath: /data # where data is mounted inside component                
        - name: wasi-ai-app-summarizer
          image: ghcr.io/bharattech/wasi-ai-app-summarizer:0.2.0
          localResources:
            volumeMounts:
              - name: wasmcloud-data
                mountPath: /data # where data is mounted inside component                
      hostInterfaces:
        - namespace: wasi
          package: http
          interfaces:
            - handler
          config:
            host: localhost
