apiVersion: v1
kind: Pod
metadata:
  name: temp-copier
  namespace: wasmcloud
spec:
  volumes:
    - name: data-vol
      hostPath:
        path: /var/data
  containers:
    - name: copier
      image: alpine
      command: ["sleep", "3600"]
      volumeMounts:
        - name: data-vol
          mountPath: /mnt/data
  securityContext:
    runAsUser: 0          # root
    runAsGroup: 0