package wasmcloud:example;

world example {
  import wasi:keyvalue/atomics@0.2.0-draft; 
  import wasi:keyvalue/store@0.2.0-draft; 
  import wasi:logging/logging@0.1.0-draft;

  import wasmcloud:secrets/store@0.1.0-draft;
  import wasmcloud:secrets/reveal@0.1.0-draft;

  export wasi:http/incoming-handler@0.2.0;
}
