# capability-provider/httpclient/Makefile

CAPABILITY_ID = wasmcloud:httpclient
NAME = "HttpClient"
VENDOR = "wasmcloud"
PROJECT = httpclient
VERSION = 0.2.0
REVISION = 0

include ../build/makefiles/provider.mk

test:
	cargo test -- --nocapture

