package wasmcloud:component;

/// All interfaces provided by the host. This may change in backwards-incompatible way.
world interfaces {
    import wasmcloud:bus/lattice@1.0.0;

    import wasi:blobstore/blobstore@0.2.0-draft;
    import wasi:config/store@0.2.0-draft;
    import wasi:http/outgoing-handler@0.2.2;
    import wasi:keyvalue/atomics@0.2.0-draft;
    import wasi:keyvalue/store@0.2.0-draft;
    import wasi:keyvalue/batch@0.2.0-draft;
    import wasi:logging/logging@0.1.0-draft;
    import wasi:random/random@0.2.2;

    import wasmcloud:messaging/consumer@0.2.0;
}
