{{- if .Values.nats.enabled }}
{{- $registry := .Values.nats.image.registry | default .Values.global.image.registry -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats
  namespace: {{ .Release.Namespace }}
  labels:
    wasmcloud.com/name: nats
    {{- include "runtime-operator.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      wasmcloud.com/name: nats
  template:
    metadata:
      labels:
        wasmcloud.com/name: nats
        {{- include "nats.podLabels" . | nindent 8 }}
      {{- with .Values.nats.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      volumes:
        - name: nats-config
          configMap:
            name: nats
        {{- if $.Values.global.tls.enabled }}
        - name: nats-cert
          secret:
            secretName: {{ .Values.global.certificates.natsCertSecretName }}
        {{- end }}
      serviceAccountName: {{ include "nats.serviceAccountName" . }}
      {{- include "runtime-operator.imagePullSecrets" . | nindent 6 }}
      containers:
        - name: nats
          image: {{ if $registry }}{{ printf "%s/%s" $registry .Values.nats.image.repository }}{{ else }}{{ .Values.nats.image.repository }}{{ end }}:{{ .Values.nats.image.tag | default "latest" }}
          args:
            - "-DV"
            - "-c"
            - "/nats-config/nats-server.conf"
          imagePullPolicy: {{ .Values.nats.image.pull_policy }}
          volumeMounts:
            - name: nats-config
              mountPath: /nats-config
            {{- if $.Values.global.tls.enabled }}
            - name: nats-cert
              mountPath: /nats-cert
            {{- end }}
          ports:
            - name: tcp-nats
              containerPort: 4222
          securityContext:
            capabilities:
              drop:
                - NET_RAW
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 0
{{- end }}