package wasmcloud:actor

/// All interfaces provided by the host. This may change in backwards-incompatible way.
world interfaces {
    import wasmcloud:bus/host
    import wasmcloud:bus/guest-config

    import wasi:blobstore/blobstore
    import wasi:keyvalue/atomic
    import wasi:keyvalue/readwrite
    import wasi:logging/logging@0.2.0-rc-2023-10-18
    import wasi:random/random@0.2.0-rc-2023-10-18

    import wasmcloud:messaging/consumer
}
