//! Acquiring the template index: the published `catalog.json` is fetched when
//! reachable (one small request instead of a clone); otherwise the repository
//! is shallow-cloned and every project derived from source on the spot.

use std::path::{Path, PathBuf};
use std::time::{Duration, SystemTime};

use anyhow::{Context as _, Result, bail};
use tracing::{debug, warn};
use wash_topology::Topology;
use wash_topology::catalog::from_catalog_json;

use crate::new::clone_template;

/// Repository the curated templates live in. Always read.
pub const TEMPLATE_REPO: &str = "https://github.com/wasmCloud/wasmCloud.git";

/// Community contributions, read only when the user asks for them.
pub const EXPERIMENTAL_REPO: &str = "https://github.com/wasmCloud/awesome-wasmcloud.git";

/// Published catalogs, regenerated by each repo's CI. Overridable for mirrors
/// and tests via `WASH_WIZARD_CATALOG_URL` / `WASH_WIZARD_COMMUNITY_CATALOG_URL`.
const CATALOG_URL: &str =
    "https://raw.githubusercontent.com/wasmCloud/wasmCloud/main/catalog.json";
const EXPERIMENTAL_CATALOG_URL: &str =
    "https://raw.githubusercontent.com/wasmCloud/awesome-wasmcloud/main/catalog.json";

/// Cache subdirectories holding each clone, and files holding each fetched catalog.
const CACHE_SUBDIR: &str = "wizard-templates";
const EXPERIMENTAL_SUBDIR: &str = "wizard-experimental";
const CATALOG_CACHE: &str = "wizard-catalog.json";
const EXPERIMENTAL_CATALOG_CACHE: &str = "wizard-community-catalog.json";

/// How long a fetched catalog or community clone is reused before refetching.
const CATALOG_TTL: Duration = Duration::from_secs(60 * 60 * 24);

fn catalog_url() -> String {
    std::env::var("WASH_WIZARD_CATALOG_URL").unwrap_or_else(|_| CATALOG_URL.to_string())
}

fn community_catalog_url() -> String {
    std::env::var("WASH_WIZARD_COMMUNITY_CATALOG_URL")
        .unwrap_or_else(|_| EXPERIMENTAL_CATALOG_URL.to_string())
}

/// Where the index was read from, so the caller can say so.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Source {
    /// The published catalog, fetched or served from its cache.
    Catalog,
    /// Freshly cloned during this run.
    Cloned,
    /// Reused from a previous run's clone.
    Cache,
    /// Read from a directory the caller named.
    Local,
    /// Auto-detected wasmCloud checkout around the working directory.
    Checkout,
    /// The community repository, behind the experimental toggle.
    Experimental,
}

/// The indexed architectures plus where they came from.
pub struct Index {
    pub topologies: Vec<Topology>,
    pub source: Source,
    pub root: PathBuf,
    /// Source of each entry, parallel to `topologies` by position — anything
    /// that reorders one must reorder the other.
    pub origins: Vec<Source>,
    /// Whether the community source was read.
    pub experimental: bool,
    /// How long ago the community clone was fetched, when it was read.
    pub community_age: Option<Duration>,
}

impl Index {
    /// The repository a listed architecture is scaffolded from. Matched by
    /// address rather than id: ids are unique only within a source.
    pub fn repo_for(&self, topology: &Topology) -> &'static str {
        let community = self
            .topologies
            .iter()
            .position(|candidate| std::ptr::eq(candidate, topology))
            .and_then(|at| self.origins.get(at))
            .is_some_and(|origin| *origin == Source::Experimental);
        if community {
            EXPERIMENTAL_REPO
        } else {
            TEMPLATE_REPO
        }
    }
}

/// Load the index: published catalog first, clone-and-derive as the fallback.
pub async fn load(
    cache_dir: &Path,
    working_dir: &Path,
    local: Option<&Path>,
    refresh: bool,
    experimental: bool,
) -> Result<Index> {
    let community = spawn_community(cache_dir, refresh, experimental);

    if let Some(root) = local {
        let topologies = derive_entries(root).await?;
        let origins = vec![Source::Local; topologies.len()];
        return with_community(
            Index {
                topologies,
                source: Source::Local,
                root: root.to_path_buf(),
                origins,
                experimental: false,
                community_age: None,
            },
            community,
        )
        .await;
    }

    // Prefer a surrounding checkout, but only when it carries derivable projects.
    if !refresh && let Some(root) = find_checkout(working_dir) {
        let topologies = derive_entries(&root).await?;
        if !topologies.is_empty() {
            debug!(root = %root.display(), "using templates from the surrounding checkout");
            let origins = vec![Source::Checkout; topologies.len()];
            return with_community(
                Index {
                    topologies,
                    source: Source::Checkout,
                    root,
                    origins,
                    experimental: false,
                    community_age: None,
                },
                community,
            )
            .await;
        }
    }

    // The published catalog: one small fetch instead of a whole clone. An
    // empty document reads as a broken publish, not an empty repo — fall
    // through to the clone rather than showing nothing.
    let catalog_cache = cache_dir.join(CATALOG_CACHE);
    if let Some(topologies) = fetch_catalog(&catalog_url(), &catalog_cache, refresh).await
        && !topologies.is_empty()
    {
        let origins = vec![Source::Catalog; topologies.len()];
        return with_community(
            Index {
                topologies,
                source: Source::Catalog,
                root: catalog_cache,
                origins,
                experimental: false,
                community_age: None,
            },
            community,
        )
        .await;
    }

    let root = cache_dir.join(CACHE_SUBDIR);
    let cached = root.join("templates").is_dir();
    if cached && !refresh {
        debug!(root = %root.display(), "using cached template clone");
    }

    let source = match fetch_into(&root, TEMPLATE_REPO, refresh || !cached).await? {
        true => Source::Cloned,
        false => Source::Cache,
    };

    let topologies = derive_entries(&root).await?;
    let origins = vec![source; topologies.len()];

    with_community(
        Index {
            topologies,
            source,
            root,
            origins,
            experimental: false,
            community_age: None,
        },
        community,
    )
    .await
}

/// Fetch a published catalog, preferring a fresh-enough cached copy. `None`
/// when neither network nor cache can supply one — callers fall back to a clone.
async fn fetch_catalog(url: &str, cache_file: &Path, refresh: bool) -> Option<Vec<Topology>> {
    let cached = || async {
        let raw = tokio::fs::read_to_string(cache_file).await.ok()?;
        parse_catalog(&raw)
    };
    let stale = cache_age(cache_file).is_none_or(|age| age >= CATALOG_TTL);
    if !refresh
        && !stale
        && let Some(entries) = cached().await
    {
        return Some(entries);
    }
    match fetch_text(url).await {
        Ok(raw) => match parse_catalog(&raw) {
            Some(entries) => {
                if let Err(err) = tokio::fs::write(cache_file, &raw).await {
                    warn!(error = ?err, "failed to cache the fetched catalog");
                }
                Some(entries)
            }
            // Damaged or newer-schema document: a stale cached copy beats none.
            None => cached().await,
        },
        Err(err) => {
            debug!(error = ?err, url, "catalog fetch failed; trying the cached copy");
            cached().await
        }
    }
}

/// Parse and sort catalog entries the way the picker groups them.
fn parse_catalog(raw: &str) -> Option<Vec<Topology>> {
    match from_catalog_json(raw) {
        Ok(mut entries) => {
            entries.sort_by(|a, b| {
                a.shape
                    .rank()
                    .cmp(&b.shape.rank())
                    .then_with(|| a.id.cmp(&b.id))
            });
            Some(entries)
        }
        Err(err) => {
            warn!(error = ?err, "unreadable catalog");
            None
        }
    }
}

async fn fetch_text(url: &str) -> Result<String> {
    let response = reqwest::Client::builder()
        .timeout(Duration::from_secs(10))
        .build()
        .context("failed to build an HTTP client")?
        .get(url)
        .send()
        .await
        .with_context(|| format!("failed to fetch {url}"))?
        .error_for_status()
        .with_context(|| format!("{url} answered an error"))?;
    response
        .text()
        .await
        .with_context(|| format!("failed to read {url}"))
}

/// Start the community load without waiting on it, so it overlaps the curated
/// path. Published catalog first, clone-and-derive as the fallback.
fn spawn_community(
    cache_dir: &Path,
    refresh: bool,
    experimental: bool,
) -> Option<tokio::task::JoinHandle<Result<(Vec<Topology>, Option<Duration>)>>> {
    if !experimental {
        return None;
    }
    let cache_dir = cache_dir.to_path_buf();
    Some(tokio::spawn(async move {
        let cache_file = cache_dir.join(EXPERIMENTAL_CATALOG_CACHE);
        if let Some(entries) = fetch_catalog(&community_catalog_url(), &cache_file, refresh).await
        {
            // An empty community catalog is a legitimate state; the pane says so.
            return Ok((entries, cache_age(&cache_file)));
        }
        let dir = cache_dir.join(EXPERIMENTAL_SUBDIR);
        let stale = cache_age(&dir).is_none_or(|age| age >= CATALOG_TTL);
        fetch_into(&dir, EXPERIMENTAL_REPO, refresh || stale).await?;
        Ok((derive_entries(&dir).await?, cache_age(&dir)))
    }))
}

async fn with_community(
    mut index: Index,
    fetch: Option<tokio::task::JoinHandle<Result<(Vec<Topology>, Option<Duration>)>>>,
) -> Result<Index> {
    let Some(fetch) = fetch else {
        return Ok(index);
    };
    match fetch.await.context("the community fetch task died")? {
        Ok((extra, age)) => {
            index
                .origins
                .extend(std::iter::repeat_n(Source::Experimental, extra.len()));
            index.topologies.extend(extra);
            // Read even if it held nothing, so the picker can say so.
            index.experimental = true;
            index.community_age = age;
        }
        // A failed community load must not take the curated set down.
        Err(err) => warn!(error = ?err, "failed to load experimental templates"),
    }
    Ok(index)
}

/// How long ago `dir` was written; `None` (absent or unreadable) reads as stale.
fn cache_age(dir: &Path) -> Option<Duration> {
    let modified = std::fs::metadata(dir).ok()?.modified().ok()?;
    SystemTime::now().duration_since(modified).ok()
}

/// Put a copy of `repo` at `dir`, fetching only when `refetch`; reports whether
/// a fresh copy landed. Staged in a sibling and renamed into place so a failed
/// fetch keeps the existing cache.
async fn fetch_into(dir: &Path, repo: &str, refetch: bool) -> Result<bool> {
    if !refetch && dir.exists() {
        return Ok(false);
    }
    // `clone_template` needs an empty destination.
    let staging = dir.with_extension("fetching");
    if staging.exists() {
        tokio::fs::remove_dir_all(&staging)
            .await
            .with_context(|| format!("failed to clear {}", staging.display()))?;
    }

    match clone_template(repo, &staging, None).await {
        Ok(()) => {
            if dir.exists() {
                tokio::fs::remove_dir_all(dir)
                    .await
                    .with_context(|| format!("failed to clear {}", dir.display()))?;
            }
            tokio::fs::rename(&staging, dir)
                .await
                .with_context(|| format!("failed to move {} into place", staging.display()))?;
            Ok(true)
        }
        Err(err) if dir.exists() => {
            warn!(error = ?err, repo, "failed to refresh; keeping the cached copy");
            tokio::fs::remove_dir_all(&staging).await.ok();
            Ok(false)
        }
        Err(err) => {
            tokio::fs::remove_dir_all(&staging).await.ok();
            Err(err).with_context(|| format!("failed to fetch {repo}"))
        }
    }
}

/// Walk up from `start` for a wasmCloud checkout: `templates/` plus a workspace
/// `Cargo.toml`.
fn find_checkout(start: &Path) -> Option<PathBuf> {
    let mut dir = start.to_path_buf();
    loop {
        if dir.join("templates").is_dir() && dir.join("Cargo.toml").is_file() {
            return Some(dir);
        }
        if !dir.pop() {
            return None;
        }
    }
}

/// Derive an entry for every project under `root`, sorted by shape rank then id.
pub async fn derive_entries(root: &Path) -> Result<Vec<Topology>> {
    let root = root.to_path_buf();
    // Derivation is synchronous fs probing; keep it off the interactive executor.
    let mut topologies = tokio::task::spawn_blocking(move || {
        let mut entries = Vec::new();
        for project in wash_topology::derive::discover(&root) {
            let rel = project
                .strip_prefix(&root)
                .unwrap_or(&project)
                .to_string_lossy()
                .replace('\\', "/");
            match wash_topology::derive(&project, &rel) {
                Ok(topology) => entries.push(topology),
                Err(err) => {
                    warn!(project = %project.display(), error = ?err, "skipping underivable project");
                }
            }
        }

        let mut stubs = Vec::new();
        collect_stubs(&root, &mut stubs, 0);
        for path in stubs {
            let parsed = std::fs::read_to_string(&path)
                .map_err(anyhow::Error::from)
                .and_then(|raw| serde_yaml_ng::from_str::<Topology>(&raw).map_err(Into::into));
            match parsed {
                // A stub without an origin has nothing to clone when picked.
                Ok(stub) if stub.repo.is_some() => entries.push(stub),
                Ok(_) => warn!(path = %path.display(), "skipping a stub with no origin repository"),
                Err(err) => warn!(path = %path.display(), error = ?err, "skipping unreadable stub"),
            }
        }
        entries
    })
    .await
    .context("the derivation task died")?;

    topologies.sort_by(|a, b| {
        a.shape
            .rank()
            .cmp(&b.shape.rank())
            .then_with(|| a.id.cmp(&b.id))
    });
    Ok(topologies)
}

/// Walk for origin stubs, bounded by the same depth and descend rules as the
/// project walk, so a stub and a project at the same depth are equally visible.
fn collect_stubs(dir: &Path, found: &mut Vec<PathBuf>, depth: usize) {
    if depth > wash_topology::derive::MAX_DEPTH {
        return;
    }
    let stub = dir.join(".wash").join(STUB_NAME);
    if stub.is_file() {
        found.push(stub);
    }
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if !path.is_dir() {
            continue;
        }
        let name = entry.file_name().to_string_lossy().to_string();
        if wash_topology::derive::descends_into(&name) {
            collect_stubs(&path, found, depth + 1);
        }
    }
}

/// Filename of a linked entry's origin stub, inside its `.wash/` directory. A
/// stub carries origin and listing identity, never a graph — that is derived
/// fresh after the clone.
pub const STUB_NAME: &str = "catalog.yaml";

/// Banner every written stub carries.
const STUB_BANNER: &str = "\
# Generated: `wash wizard index --link <url>`. Do not edit by hand.
# An origin stub: this project lives in the repository named below, and its
# shape is derived from source after cloning it.
";

/// A linked entry ready to be written into a catalog.
pub struct LinkedStub {
    /// Directory the stub belongs in: `<into>/<id>`.
    pub dir: PathBuf,
    pub topology: Topology,
}

/// Build an origin stub for a project hosted in another repository, cloning it
/// once to prove the pointer is real and read a shape for the listing.
pub async fn link(repo: &str, subfolder: Option<&str>, into: &Path) -> Result<LinkedStub> {
    let checkout = tempfile::tempdir().context("failed to create a temporary directory")?;
    clone_template(repo, checkout.path(), None)
        .await
        .with_context(|| format!("failed to clone {repo}"))?;

    let project = match subfolder {
        Some(subfolder) => checkout.path().join(subfolder),
        None => checkout.path().to_path_buf(),
    };
    if !project.is_dir() {
        bail!("{repo} has no {}", subfolder.unwrap_or("(repository root)"));
    }

    let id = link_id(repo, subfolder);
    let rel = format!("{}/{id}", into.to_string_lossy().replace('\\', "/"));
    let mut topology = wash_topology::derive(&project, &rel)
        .with_context(|| format!("failed to derive a topology for {repo}"))?;

    // The derived graph is dropped: it would go stale; picking the entry derives fresh.
    topology.id = id.clone();
    topology.source = rel;
    topology.repo = Some(repo.to_string());
    topology.subfolder = subfolder.map(str::to_string);
    topology.capabilities.clear();
    topology.nodes.clear();
    topology.edges.clear();
    topology.unresolved.clear();

    Ok(LinkedStub {
        dir: into.join(id),
        topology,
    })
}

/// Write a stub under its directory, creating `.wash/` as needed; returns the path.
pub async fn write_stub(stub: &LinkedStub) -> Result<PathBuf> {
    let dir = stub.dir.join(".wash");
    tokio::fs::create_dir_all(&dir)
        .await
        .with_context(|| format!("failed to create {}", dir.display()))?;
    let path = dir.join(STUB_NAME);
    let yaml =
        serde_yaml_ng::to_string(&stub.topology).context("failed to serialize the stub")?;
    tokio::fs::write(&path, format!("{STUB_BANNER}{yaml}"))
        .await
        .with_context(|| format!("failed to write {}", path.display()))?;
    Ok(path)
}

/// Directory name for a linked entry: the subfolder's last segment, else the repository's name.
fn link_id(repo: &str, subfolder: Option<&str>) -> String {
    if let Some(last) = subfolder.and_then(|s| s.rsplit('/').find(|p| !p.is_empty())) {
        return last.to_string();
    }
    repo.trim_end_matches('/')
        .trim_end_matches(".git")
        .rsplit(['/', ':'])
        .find(|p| !p.is_empty())
        .unwrap_or("linked")
        .to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A path `git clone` refuses immediately, so failure paths need no network.
    const UNREACHABLE: &str = "/nonexistent/not-a-repository";

    /// A cache directory holding one recognisable file.
    async fn seeded_cache(root: &Path) -> PathBuf {
        let dir = root.join("wizard-experimental");
        tokio::fs::create_dir_all(&dir).await.expect("mkdir");
        tokio::fs::write(dir.join("keep-me"), "cached")
            .await
            .expect("write");
        dir
    }

    #[tokio::test]
    async fn a_fresh_enough_cache_is_reused_untouched() {
        let tempdir = tempfile::tempdir().expect("tempdir");
        let dir = seeded_cache(tempdir.path()).await;

        assert!(
            !fetch_into(&dir, UNREACHABLE, false)
                .await
                .expect("reuse must not even try to fetch"),
            "nothing should have been fetched"
        );
        assert!(dir.join("keep-me").is_file());
    }

    #[tokio::test]
    async fn a_failed_refetch_keeps_the_copy_that_was_already_there() {
        // Regression: clearing before fetching destroyed the cache on a failed --refresh.
        let tempdir = tempfile::tempdir().expect("tempdir");
        let dir = seeded_cache(tempdir.path()).await;

        let fetched = fetch_into(&dir, UNREACHABLE, true)
            .await
            .expect("a failed refresh over a usable cache is not an error");
        assert!(!fetched, "nothing landed");
        assert!(
            dir.join("keep-me").is_file(),
            "the cached copy must survive a failed refresh"
        );
        assert!(
            !dir.with_extension("fetching").exists(),
            "and the staging directory must not be left behind"
        );
    }

    #[tokio::test]
    async fn a_failed_first_fetch_is_an_error_because_there_is_no_fallback() {
        let tempdir = tempfile::tempdir().expect("tempdir");
        let dir = tempdir.path().join("wizard-experimental");

        let err = fetch_into(&dir, UNREACHABLE, true)
            .await
            .expect_err("nothing to fall back to");
        assert!(format!("{err:#}").contains("failed to fetch"), "{err:#}");
        assert!(!dir.with_extension("fetching").exists());
    }

    #[test]
    fn a_missing_cache_reads_as_stale_rather_than_current() {
        let tempdir = tempfile::tempdir().expect("tempdir");
        let missing = tempdir.path().join("never-fetched");
        assert!(cache_age(&missing).is_none());
        assert!(cache_age(&missing).is_none_or(|age| age >= CATALOG_TTL));
    }

    #[test]
    fn a_directory_just_written_is_within_the_ttl() {
        let tempdir = tempfile::tempdir().expect("tempdir");
        let age = cache_age(tempdir.path()).expect("a real directory has a time");
        assert!(age < CATALOG_TTL, "{age:?}");
    }

    /// A minimal derivable project: a `.wash/config.yaml` naming its component.
    async fn seeded_project(root: &Path, name: &str) {
        let dir = root.join(name).join(".wash");
        tokio::fs::create_dir_all(&dir).await.expect("mkdir");
        tokio::fs::write(
            dir.join("config.yaml"),
            format!("build:\n  component_path: target/{name}.wasm\n"),
        )
        .await
        .expect("write config");
    }

    /// An origin stub as `wash wizard index --link` writes it: identity and origin, no graph.
    async fn seeded_stub(root: &Path, name: &str, shape: &str) {
        let dir = root.join(name).join(".wash");
        tokio::fs::create_dir_all(&dir).await.expect("mkdir");
        tokio::fs::write(
            dir.join(STUB_NAME),
            format!(
                "schema: 1\nid: {name}\nsource: linked/{name}\n\
                 repo: https://github.com/someone/{name}\nshape: {shape}\nnodes: []\n"
            ),
        )
        .await
        .expect("write stub");
    }

    #[tokio::test]
    async fn derives_projects_and_orders_structured_shapes_first() {
        let tempdir = tempfile::tempdir().expect("tempdir");
        // The chain outranks the single regardless of names.
        seeded_stub(tempdir.path(), "z-chain", "chain").await;
        seeded_project(tempdir.path(), "a-single").await;

        let topologies = derive_entries(tempdir.path()).await.expect("derive");

        assert_eq!(topologies.len(), 2);
        assert_eq!(topologies[0].id, "z-chain");
        assert_eq!(topologies[1].id, "a-single");
        assert!(!topologies[1].nodes.is_empty());
        assert!(topologies[0].nodes.is_empty());
    }

    /// A one-entry catalog document, as CI would publish it.
    fn catalog_doc() -> String {
        let entry: Topology = serde_yaml_ng::from_str(
            "schema: 1\nid: demo\nsource: templates/demo\nshape: single\nnodes: []\n",
        )
        .expect("entry");
        wash_topology::catalog::to_catalog_json(&[entry]).expect("serialize")
    }

    /// A port nothing listens on, so fetch failures need no network.
    const UNREACHABLE_URL: &str = "http://127.0.0.1:1/catalog.json";

    #[tokio::test]
    async fn a_fresh_cached_catalog_is_served_without_the_network() {
        let tempdir = tempfile::tempdir().expect("tempdir");
        let file = tempdir.path().join(CATALOG_CACHE);
        tokio::fs::write(&file, catalog_doc()).await.expect("write");

        let entries = fetch_catalog(UNREACHABLE_URL, &file, false)
            .await
            .expect("a fresh cache needs no network");
        assert_eq!(entries.len(), 1);
        assert_eq!(entries[0].id, "demo");
    }

    #[tokio::test]
    async fn a_failed_refetch_falls_back_to_the_cached_catalog() {
        let tempdir = tempfile::tempdir().expect("tempdir");
        let file = tempdir.path().join(CATALOG_CACHE);
        tokio::fs::write(&file, catalog_doc()).await.expect("write");

        // `refresh` forces a fetch attempt; the refusal must not lose the copy.
        let entries = fetch_catalog(UNREACHABLE_URL, &file, true)
            .await
            .expect("a stale copy beats none");
        assert_eq!(entries[0].id, "demo");
    }

    #[tokio::test]
    async fn no_catalog_anywhere_reads_as_none_so_the_clone_path_runs() {
        let tempdir = tempfile::tempdir().expect("tempdir");
        let file = tempdir.path().join(CATALOG_CACHE);

        assert!(fetch_catalog(UNREACHABLE_URL, &file, false).await.is_none());
    }

    #[tokio::test]
    async fn a_stub_without_an_origin_is_not_listed() {
        let tempdir = tempfile::tempdir().expect("tempdir");
        let dir = tempdir.path().join("orphan").join(".wash");
        tokio::fs::create_dir_all(&dir).await.expect("mkdir");
        tokio::fs::write(
            dir.join(STUB_NAME),
            "schema: 1\nid: orphan\nsource: linked/orphan\nshape: single\nnodes: []\n",
        )
        .await
        .expect("write stub");

        let topologies = derive_entries(tempdir.path()).await.expect("derive");
        assert!(topologies.is_empty());
    }

    #[test]
    fn a_checkout_is_found_from_a_nested_directory() {
        let tempdir = tempfile::tempdir().expect("tempdir");
        let root = tempdir.path();
        std::fs::create_dir_all(root.join("templates/http-handler/src")).expect("mkdir");
        std::fs::write(root.join("Cargo.toml"), "[workspace]\n").expect("write");

        let found = find_checkout(&root.join("templates/http-handler/src"))
            .expect("should walk up to the checkout root");
        assert_eq!(found, root);
    }

    #[test]
    fn a_plain_directory_is_not_mistaken_for_a_checkout() {
        let tempdir = tempfile::tempdir().expect("tempdir");
        // A Cargo project without templates/ is somebody else's crate.
        std::fs::write(tempdir.path().join("Cargo.toml"), "[package]\n").expect("write");

        assert!(find_checkout(tempdir.path()).is_none());
    }

    #[tokio::test]
    async fn an_underivable_project_does_not_hide_the_others() {
        let tempdir = tempfile::tempdir().expect("tempdir");
        seeded_project(tempdir.path(), "good").await;

        // Unparseable config: derivation fails, the rest of the catalog survives.
        let bad = tempdir.path().join("bad").join(".wash");
        tokio::fs::create_dir_all(&bad).await.expect("mkdir");
        tokio::fs::write(bad.join("config.yaml"), "this: [is not: a config")
            .await
            .expect("write");

        let topologies = derive_entries(tempdir.path()).await.expect("derive");

        assert_eq!(topologies.len(), 1);
        assert_eq!(topologies[0].id, "good");
    }
}
