{{- if and .Values.operator.enabled .Values.operator.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "runtime-operator.fullname" . }}
  labels:
    {{- include "runtime-operator.labels" . | nindent 4 }}
  annotations: {}
rules:
  - apiGroups:
    - runtime.wasmcloud.dev
    resources:
    - artifacts
    - hosts
    - workloads
    - workloadreplicasets
    - workloaddeployments
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - runtime.wasmcloud.dev
    resources:
    - artifacts/status
    - hosts/status
    - workloads/status
    - workloadreplicasets/status
    - workloaddeployments/status
    verbs:
    - get
    - update
    - patch
  - apiGroups:
    - ""
    resources:
    - configmaps
    - secrets
    - namespaces
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ""
    resources:
    - events
    verbs:
    - create
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - ""
    resources:
    - services
    verbs:
    - get
    - list
    - watch
  {{- if not .Values.operator.watchNamespaces }}
  # If the operator is watching all namespaces, it needs permissions to manage EndpointSlices across the cluster. If it's only watching specific
  # namespaces, a more limited Role and RoleBinding will be created in each namespace instead, and this ClusterRole will not include permissions
  # for EndpointSlices. See https://wasmcloud.com/docs/kubernetes-operator/operator-manual/roles-and-rolebindings/#restricting-access-of-the-operator-to-namespaces
  # for more details.
  - apiGroups:
    - discovery.k8s.io
    resources:
    - endpointslices
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  {{- end }}
{{- end }}
