package wasmcloud:httpclient;

/// This interface represents the functions necessary
/// to implement the [httpclient wasmCloud interface](https://github.com/wasmCloud/interfaces/blob/main/httpclient)
///
/// Derived from https://github.com/wasmCloud/interfaces/blob/main/httpclient/httpclient.smithy
///
interface http-client {
    /// Request to be sent over HTTP
    record http-request {
      /// HTTP method
      method: string,
      /// URL to which the request should be made
      url: string,
      /// Headers to accompany the HTTP request
      headers-map: list<tuple<string, list<string>>>,
      /// Body to send with the HTTP request
      body: list<u8>,
    }

    /// Response received over HTTP
    record http-response {
      /// HTTP status code
      status-code: u16,
      /// Headers that were received with the response
      header-map: list<tuple<string, list<string>>>,
      /// Body to send with the HTTP request
      body: list<u8>,
    }

    /// Perform an HTTP request
    request: func(input: http-request) -> http-response;
}
