// Generated by `wit-bindgen` 0.33.0. DO NOT EDIT!
#ifndef __BINDINGS_HELLO_H
#define __BINDINGS_HELLO_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct hello_string_t {
  uint8_t*ptr;
  size_t len;
} hello_string_t;

typedef struct wasi_io_poll_own_pollable_t {
  int32_t __handle;
} wasi_io_poll_own_pollable_t;

typedef struct wasi_io_poll_borrow_pollable_t {
  int32_t __handle;
} wasi_io_poll_borrow_pollable_t;

typedef struct {
  wasi_io_poll_borrow_pollable_t *ptr;
  size_t len;
} wasi_io_poll_list_borrow_pollable_t;

typedef struct {
  uint32_t *ptr;
  size_t len;
} hello_list_u32_t;

typedef uint64_t wasi_clocks_monotonic_clock_instant_t;

typedef uint64_t wasi_clocks_monotonic_clock_duration_t;

typedef wasi_io_poll_own_pollable_t wasi_clocks_monotonic_clock_own_pollable_t;

typedef struct wasi_io_error_own_error_t {
  int32_t __handle;
} wasi_io_error_own_error_t;

typedef struct wasi_io_error_borrow_error_t {
  int32_t __handle;
} wasi_io_error_borrow_error_t;

typedef wasi_io_error_own_error_t wasi_io_streams_own_error_t;

typedef struct wasi_io_streams_stream_error_t {
  uint8_t tag;
  union {
    wasi_io_streams_own_error_t     last_operation_failed;
  } val;
} wasi_io_streams_stream_error_t;

#define WASI_IO_STREAMS_STREAM_ERROR_LAST_OPERATION_FAILED 0
#define WASI_IO_STREAMS_STREAM_ERROR_CLOSED 1

typedef struct wasi_io_streams_own_input_stream_t {
  int32_t __handle;
} wasi_io_streams_own_input_stream_t;

typedef struct wasi_io_streams_borrow_input_stream_t {
  int32_t __handle;
} wasi_io_streams_borrow_input_stream_t;

typedef struct wasi_io_streams_own_output_stream_t {
  int32_t __handle;
} wasi_io_streams_own_output_stream_t;

typedef struct wasi_io_streams_borrow_output_stream_t {
  int32_t __handle;
} wasi_io_streams_borrow_output_stream_t;

typedef struct {
  uint8_t *ptr;
  size_t len;
} hello_list_u8_t;

typedef struct {
  bool is_err;
  union {
    hello_list_u8_t ok;
    wasi_io_streams_stream_error_t err;
  } val;
} wasi_io_streams_result_list_u8_stream_error_t;

typedef struct {
  bool is_err;
  union {
    uint64_t ok;
    wasi_io_streams_stream_error_t err;
  } val;
} wasi_io_streams_result_u64_stream_error_t;

typedef wasi_io_poll_own_pollable_t wasi_io_streams_own_pollable_t;

typedef struct {
  bool is_err;
  union {
    wasi_io_streams_stream_error_t err;
  } val;
} wasi_io_streams_result_void_stream_error_t;

typedef wasi_clocks_monotonic_clock_duration_t wasi_http_types_duration_t;

// This type corresponds to HTTP standard Methods.
typedef struct wasi_http_types_method_t {
  uint8_t tag;
  union {
    hello_string_t     other;
  } val;
} wasi_http_types_method_t;

#define WASI_HTTP_TYPES_METHOD_GET 0
#define WASI_HTTP_TYPES_METHOD_HEAD 1
#define WASI_HTTP_TYPES_METHOD_POST 2
#define WASI_HTTP_TYPES_METHOD_PUT 3
#define WASI_HTTP_TYPES_METHOD_DELETE 4
#define WASI_HTTP_TYPES_METHOD_CONNECT 5
#define WASI_HTTP_TYPES_METHOD_OPTIONS 6
#define WASI_HTTP_TYPES_METHOD_TRACE 7
#define WASI_HTTP_TYPES_METHOD_PATCH 8
#define WASI_HTTP_TYPES_METHOD_OTHER 9

// This type corresponds to HTTP standard Related Schemes.
typedef struct wasi_http_types_scheme_t {
  uint8_t tag;
  union {
    hello_string_t     other;
  } val;
} wasi_http_types_scheme_t;

#define WASI_HTTP_TYPES_SCHEME_HTTP 0
#define WASI_HTTP_TYPES_SCHEME_HTTPS 1
#define WASI_HTTP_TYPES_SCHEME_OTHER 2

typedef struct {
  bool is_some;
  hello_string_t val;
} hello_option_string_t;

typedef struct {
  bool is_some;
  uint16_t val;
} hello_option_u16_t;

// Defines the case payload type for `DNS-error` above:
typedef struct wasi_http_types_dns_error_payload_t {
  hello_option_string_t   rcode;
  hello_option_u16_t   info_code;
} wasi_http_types_dns_error_payload_t;

typedef struct {
  bool is_some;
  uint8_t val;
} hello_option_u8_t;

// Defines the case payload type for `TLS-alert-received` above:
typedef struct wasi_http_types_tls_alert_received_payload_t {
  hello_option_u8_t   alert_id;
  hello_option_string_t   alert_message;
} wasi_http_types_tls_alert_received_payload_t;

typedef struct {
  bool is_some;
  uint32_t val;
} hello_option_u32_t;

// Defines the case payload type for `HTTP-response-{header,trailer}-size` above:
typedef struct wasi_http_types_field_size_payload_t {
  hello_option_string_t   field_name;
  hello_option_u32_t   field_size;
} wasi_http_types_field_size_payload_t;

typedef struct {
  bool is_some;
  uint64_t val;
} hello_option_u64_t;

typedef struct {
  bool is_some;
  wasi_http_types_field_size_payload_t val;
} wasi_http_types_option_field_size_payload_t;

// These cases are inspired by the IANA HTTP Proxy Error Types:
// https://www.iana.org/assignments/http-proxy-status/http-proxy-status.xhtml#table-http-proxy-error-types
typedef struct wasi_http_types_error_code_t {
  uint8_t tag;
  union {
    wasi_http_types_dns_error_payload_t     dns_error;
    wasi_http_types_tls_alert_received_payload_t     tls_alert_received;
    hello_option_u64_t     http_request_body_size;
    hello_option_u32_t     http_request_header_section_size;
    wasi_http_types_option_field_size_payload_t     http_request_header_size;
    hello_option_u32_t     http_request_trailer_section_size;
    wasi_http_types_field_size_payload_t     http_request_trailer_size;
    hello_option_u32_t     http_response_header_section_size;
    wasi_http_types_field_size_payload_t     http_response_header_size;
    hello_option_u64_t     http_response_body_size;
    hello_option_u32_t     http_response_trailer_section_size;
    wasi_http_types_field_size_payload_t     http_response_trailer_size;
    hello_option_string_t     http_response_transfer_coding;
    hello_option_string_t     http_response_content_coding;
    hello_option_string_t     internal_error;
  } val;
} wasi_http_types_error_code_t;

#define WASI_HTTP_TYPES_ERROR_CODE_DNS_TIMEOUT 0
#define WASI_HTTP_TYPES_ERROR_CODE_DNS_ERROR 1
#define WASI_HTTP_TYPES_ERROR_CODE_DESTINATION_NOT_FOUND 2
#define WASI_HTTP_TYPES_ERROR_CODE_DESTINATION_UNAVAILABLE 3
#define WASI_HTTP_TYPES_ERROR_CODE_DESTINATION_IP_PROHIBITED 4
#define WASI_HTTP_TYPES_ERROR_CODE_DESTINATION_IP_UNROUTABLE 5
#define WASI_HTTP_TYPES_ERROR_CODE_CONNECTION_REFUSED 6
#define WASI_HTTP_TYPES_ERROR_CODE_CONNECTION_TERMINATED 7
#define WASI_HTTP_TYPES_ERROR_CODE_CONNECTION_TIMEOUT 8
#define WASI_HTTP_TYPES_ERROR_CODE_CONNECTION_READ_TIMEOUT 9
#define WASI_HTTP_TYPES_ERROR_CODE_CONNECTION_WRITE_TIMEOUT 10
#define WASI_HTTP_TYPES_ERROR_CODE_CONNECTION_LIMIT_REACHED 11
#define WASI_HTTP_TYPES_ERROR_CODE_TLS_PROTOCOL_ERROR 12
#define WASI_HTTP_TYPES_ERROR_CODE_TLS_CERTIFICATE_ERROR 13
#define WASI_HTTP_TYPES_ERROR_CODE_TLS_ALERT_RECEIVED 14
#define WASI_HTTP_TYPES_ERROR_CODE_HTTP_REQUEST_DENIED 15
#define WASI_HTTP_TYPES_ERROR_CODE_HTTP_REQUEST_LENGTH_REQUIRED 16
#define WASI_HTTP_TYPES_ERROR_CODE_HTTP_REQUEST_BODY_SIZE 17
#define WASI_HTTP_TYPES_ERROR_CODE_HTTP_REQUEST_METHOD_INVALID 18
#define WASI_HTTP_TYPES_ERROR_CODE_HTTP_REQUEST_URI_INVALID 19
#define WASI_HTTP_TYPES_ERROR_CODE_HTTP_REQUEST_URI_TOO_LONG 20
#define WASI_HTTP_TYPES_ERROR_CODE_HTTP_REQUEST_HEADER_SECTION_SIZE 21
#define WASI_HTTP_TYPES_ERROR_CODE_HTTP_REQUEST_HEADER_SIZE 22
#define WASI_HTTP_TYPES_ERROR_CODE_HTTP_REQUEST_TRAILER_SECTION_SIZE 23
#define WASI_HTTP_TYPES_ERROR_CODE_HTTP_REQUEST_TRAILER_SIZE 24
#define WASI_HTTP_TYPES_ERROR_CODE_HTTP_RESPONSE_INCOMPLETE 25
#define WASI_HTTP_TYPES_ERROR_CODE_HTTP_RESPONSE_HEADER_SECTION_SIZE 26
#define WASI_HTTP_TYPES_ERROR_CODE_HTTP_RESPONSE_HEADER_SIZE 27
#define WASI_HTTP_TYPES_ERROR_CODE_HTTP_RESPONSE_BODY_SIZE 28
#define WASI_HTTP_TYPES_ERROR_CODE_HTTP_RESPONSE_TRAILER_SECTION_SIZE 29
#define WASI_HTTP_TYPES_ERROR_CODE_HTTP_RESPONSE_TRAILER_SIZE 30
#define WASI_HTTP_TYPES_ERROR_CODE_HTTP_RESPONSE_TRANSFER_CODING 31
#define WASI_HTTP_TYPES_ERROR_CODE_HTTP_RESPONSE_CONTENT_CODING 32
#define WASI_HTTP_TYPES_ERROR_CODE_HTTP_RESPONSE_TIMEOUT 33
#define WASI_HTTP_TYPES_ERROR_CODE_HTTP_UPGRADE_FAILED 34
#define WASI_HTTP_TYPES_ERROR_CODE_HTTP_PROTOCOL_ERROR 35
#define WASI_HTTP_TYPES_ERROR_CODE_LOOP_DETECTED 36
#define WASI_HTTP_TYPES_ERROR_CODE_CONFIGURATION_ERROR 37
// This is a catch-all error for anything that doesn't fit cleanly into a
// more specific case. It also includes an optional string for an
// unstructured description of the error. Users should not depend on the
// string for diagnosing errors, as it's not required to be consistent
// between implementations.
#define WASI_HTTP_TYPES_ERROR_CODE_INTERNAL_ERROR 38

// This type enumerates the different kinds of errors that may occur when
// setting or appending to a `fields` resource.
typedef struct wasi_http_types_header_error_t {
  uint8_t tag;
} wasi_http_types_header_error_t;

// This error indicates that a `field-key` or `field-value` was
// syntactically invalid when used with an operation that sets headers in a
// `fields`.
#define WASI_HTTP_TYPES_HEADER_ERROR_INVALID_SYNTAX 0
// This error indicates that a forbidden `field-key` was used when trying
// to set a header in a `fields`.
#define WASI_HTTP_TYPES_HEADER_ERROR_FORBIDDEN 1
// This error indicates that the operation on the `fields` was not
// permitted because the fields are immutable.
#define WASI_HTTP_TYPES_HEADER_ERROR_IMMUTABLE 2

// Field keys are always strings.
typedef hello_string_t wasi_http_types_field_key_t;

// Field values should always be ASCII strings. However, in
// reality, HTTP implementations often have to interpret malformed values,
// so they are provided as a list of bytes.
typedef struct wasi_http_types_field_value_t {
  uint8_t   *ptr;
  size_t len;
} wasi_http_types_field_value_t;

typedef struct wasi_http_types_own_fields_t {
  int32_t __handle;
} wasi_http_types_own_fields_t;

typedef struct wasi_http_types_borrow_fields_t {
  int32_t __handle;
} wasi_http_types_borrow_fields_t;

typedef struct wasi_http_types_own_incoming_request_t {
  int32_t __handle;
} wasi_http_types_own_incoming_request_t;

typedef struct wasi_http_types_borrow_incoming_request_t {
  int32_t __handle;
} wasi_http_types_borrow_incoming_request_t;

typedef struct wasi_http_types_own_outgoing_request_t {
  int32_t __handle;
} wasi_http_types_own_outgoing_request_t;

typedef struct wasi_http_types_borrow_outgoing_request_t {
  int32_t __handle;
} wasi_http_types_borrow_outgoing_request_t;

typedef struct wasi_http_types_own_request_options_t {
  int32_t __handle;
} wasi_http_types_own_request_options_t;

typedef struct wasi_http_types_borrow_request_options_t {
  int32_t __handle;
} wasi_http_types_borrow_request_options_t;

typedef struct wasi_http_types_own_response_outparam_t {
  int32_t __handle;
} wasi_http_types_own_response_outparam_t;

typedef struct wasi_http_types_borrow_response_outparam_t {
  int32_t __handle;
} wasi_http_types_borrow_response_outparam_t;

// This type corresponds to the HTTP standard Status Code.
typedef uint16_t wasi_http_types_status_code_t;

typedef struct wasi_http_types_own_incoming_response_t {
  int32_t __handle;
} wasi_http_types_own_incoming_response_t;

typedef struct wasi_http_types_borrow_incoming_response_t {
  int32_t __handle;
} wasi_http_types_borrow_incoming_response_t;

typedef struct wasi_http_types_own_incoming_body_t {
  int32_t __handle;
} wasi_http_types_own_incoming_body_t;

typedef struct wasi_http_types_borrow_incoming_body_t {
  int32_t __handle;
} wasi_http_types_borrow_incoming_body_t;

typedef struct wasi_http_types_own_future_trailers_t {
  int32_t __handle;
} wasi_http_types_own_future_trailers_t;

typedef struct wasi_http_types_borrow_future_trailers_t {
  int32_t __handle;
} wasi_http_types_borrow_future_trailers_t;

typedef struct wasi_http_types_own_outgoing_response_t {
  int32_t __handle;
} wasi_http_types_own_outgoing_response_t;

typedef struct wasi_http_types_borrow_outgoing_response_t {
  int32_t __handle;
} wasi_http_types_borrow_outgoing_response_t;

typedef struct wasi_http_types_own_outgoing_body_t {
  int32_t __handle;
} wasi_http_types_own_outgoing_body_t;

typedef struct wasi_http_types_borrow_outgoing_body_t {
  int32_t __handle;
} wasi_http_types_borrow_outgoing_body_t;

typedef struct wasi_http_types_own_future_incoming_response_t {
  int32_t __handle;
} wasi_http_types_own_future_incoming_response_t;

typedef struct wasi_http_types_borrow_future_incoming_response_t {
  int32_t __handle;
} wasi_http_types_borrow_future_incoming_response_t;

typedef struct {
  wasi_http_types_field_key_t f0;
  wasi_http_types_field_value_t f1;
} hello_tuple2_field_key_field_value_t;

typedef struct {
  hello_tuple2_field_key_field_value_t *ptr;
  size_t len;
} hello_list_tuple2_field_key_field_value_t;

typedef struct {
  bool is_err;
  union {
    wasi_http_types_own_fields_t ok;
    wasi_http_types_header_error_t err;
  } val;
} wasi_http_types_result_own_fields_header_error_t;

typedef struct {
  wasi_http_types_field_value_t *ptr;
  size_t len;
} hello_list_field_value_t;

typedef struct {
  bool is_err;
  union {
    wasi_http_types_header_error_t err;
  } val;
} wasi_http_types_result_void_header_error_t;

typedef struct {
  bool is_some;
  wasi_http_types_scheme_t val;
} wasi_http_types_option_scheme_t;

typedef wasi_http_types_own_fields_t wasi_http_types_own_headers_t;

typedef struct {
  bool is_err;
  union {
    wasi_http_types_own_incoming_body_t ok;
  } val;
} wasi_http_types_result_own_incoming_body_void_t;

typedef struct {
  bool is_err;
  union {
    wasi_http_types_own_outgoing_body_t ok;
  } val;
} wasi_http_types_result_own_outgoing_body_void_t;

typedef struct {
  bool is_err;
} wasi_http_types_result_void_void_t;

typedef struct {
  bool is_some;
  wasi_http_types_duration_t val;
} hello_option_duration_t;

typedef struct {
  bool is_err;
  union {
    wasi_http_types_own_outgoing_response_t ok;
    wasi_http_types_error_code_t err;
  } val;
} wasi_http_types_result_own_outgoing_response_error_code_t;

typedef wasi_io_streams_own_input_stream_t wasi_http_types_own_input_stream_t;

typedef struct {
  bool is_err;
  union {
    wasi_http_types_own_input_stream_t ok;
  } val;
} wasi_http_types_result_own_input_stream_void_t;

typedef wasi_io_poll_own_pollable_t wasi_http_types_own_pollable_t;

typedef wasi_http_types_own_fields_t wasi_http_types_own_trailers_t;

typedef struct {
  bool is_some;
  wasi_http_types_own_trailers_t val;
} wasi_http_types_option_own_trailers_t;

typedef struct {
  bool is_err;
  union {
    wasi_http_types_option_own_trailers_t ok;
    wasi_http_types_error_code_t err;
  } val;
} wasi_http_types_result_option_own_trailers_error_code_t;

typedef struct {
  bool is_err;
  union {
    wasi_http_types_result_option_own_trailers_error_code_t ok;
  } val;
} wasi_http_types_result_result_option_own_trailers_error_code_void_t;

typedef struct {
  bool is_some;
  wasi_http_types_result_result_option_own_trailers_error_code_void_t val;
} wasi_http_types_option_result_result_option_own_trailers_error_code_void_t;

typedef wasi_io_streams_own_output_stream_t wasi_http_types_own_output_stream_t;

typedef struct {
  bool is_err;
  union {
    wasi_http_types_own_output_stream_t ok;
  } val;
} wasi_http_types_result_own_output_stream_void_t;

typedef struct {
  bool is_err;
  union {
    wasi_http_types_error_code_t err;
  } val;
} wasi_http_types_result_void_error_code_t;

typedef struct {
  bool is_err;
  union {
    wasi_http_types_own_incoming_response_t ok;
    wasi_http_types_error_code_t err;
  } val;
} wasi_http_types_result_own_incoming_response_error_code_t;

typedef struct {
  bool is_err;
  union {
    wasi_http_types_result_own_incoming_response_error_code_t ok;
  } val;
} wasi_http_types_result_result_own_incoming_response_error_code_void_t;

typedef struct {
  bool is_some;
  wasi_http_types_result_result_own_incoming_response_error_code_void_t val;
} wasi_http_types_option_result_result_own_incoming_response_error_code_void_t;

typedef wasi_io_error_borrow_error_t wasi_http_types_borrow_io_error_t;

typedef struct {
  bool is_some;
  wasi_http_types_error_code_t val;
} wasi_http_types_option_error_code_t;

typedef wasi_http_types_own_incoming_request_t exports_wasi_http_incoming_handler_own_incoming_request_t;

typedef wasi_http_types_own_response_outparam_t exports_wasi_http_incoming_handler_own_response_outparam_t;

// Imported Functions from `wasi:io/poll@0.2.0`
extern bool wasi_io_poll_method_pollable_ready(wasi_io_poll_borrow_pollable_t self);
extern void wasi_io_poll_method_pollable_block(wasi_io_poll_borrow_pollable_t self);
extern void wasi_io_poll_poll(wasi_io_poll_list_borrow_pollable_t *in, hello_list_u32_t *ret);

// Imported Functions from `wasi:clocks/monotonic-clock@0.2.0`
extern wasi_clocks_monotonic_clock_instant_t wasi_clocks_monotonic_clock_now(void);
extern wasi_clocks_monotonic_clock_duration_t wasi_clocks_monotonic_clock_resolution(void);
extern wasi_clocks_monotonic_clock_own_pollable_t wasi_clocks_monotonic_clock_subscribe_instant(wasi_clocks_monotonic_clock_instant_t when);
extern wasi_clocks_monotonic_clock_own_pollable_t wasi_clocks_monotonic_clock_subscribe_duration(wasi_clocks_monotonic_clock_duration_t when);

// Imported Functions from `wasi:io/error@0.2.0`
extern void wasi_io_error_method_error_to_debug_string(wasi_io_error_borrow_error_t self, hello_string_t *ret);

// Imported Functions from `wasi:io/streams@0.2.0`
extern bool wasi_io_streams_method_input_stream_read(wasi_io_streams_borrow_input_stream_t self, uint64_t len, hello_list_u8_t *ret, wasi_io_streams_stream_error_t *err);
extern bool wasi_io_streams_method_input_stream_blocking_read(wasi_io_streams_borrow_input_stream_t self, uint64_t len, hello_list_u8_t *ret, wasi_io_streams_stream_error_t *err);
extern bool wasi_io_streams_method_input_stream_skip(wasi_io_streams_borrow_input_stream_t self, uint64_t len, uint64_t *ret, wasi_io_streams_stream_error_t *err);
extern bool wasi_io_streams_method_input_stream_blocking_skip(wasi_io_streams_borrow_input_stream_t self, uint64_t len, uint64_t *ret, wasi_io_streams_stream_error_t *err);
extern wasi_io_streams_own_pollable_t wasi_io_streams_method_input_stream_subscribe(wasi_io_streams_borrow_input_stream_t self);
extern bool wasi_io_streams_method_output_stream_check_write(wasi_io_streams_borrow_output_stream_t self, uint64_t *ret, wasi_io_streams_stream_error_t *err);
extern bool wasi_io_streams_method_output_stream_write(wasi_io_streams_borrow_output_stream_t self, hello_list_u8_t *contents, wasi_io_streams_stream_error_t *err);
extern bool wasi_io_streams_method_output_stream_blocking_write_and_flush(wasi_io_streams_borrow_output_stream_t self, hello_list_u8_t *contents, wasi_io_streams_stream_error_t *err);
extern bool wasi_io_streams_method_output_stream_flush(wasi_io_streams_borrow_output_stream_t self, wasi_io_streams_stream_error_t *err);
extern bool wasi_io_streams_method_output_stream_blocking_flush(wasi_io_streams_borrow_output_stream_t self, wasi_io_streams_stream_error_t *err);
extern wasi_io_streams_own_pollable_t wasi_io_streams_method_output_stream_subscribe(wasi_io_streams_borrow_output_stream_t self);
extern bool wasi_io_streams_method_output_stream_write_zeroes(wasi_io_streams_borrow_output_stream_t self, uint64_t len, wasi_io_streams_stream_error_t *err);
extern bool wasi_io_streams_method_output_stream_blocking_write_zeroes_and_flush(wasi_io_streams_borrow_output_stream_t self, uint64_t len, wasi_io_streams_stream_error_t *err);
extern bool wasi_io_streams_method_output_stream_splice(wasi_io_streams_borrow_output_stream_t self, wasi_io_streams_borrow_input_stream_t src, uint64_t len, uint64_t *ret, wasi_io_streams_stream_error_t *err);
extern bool wasi_io_streams_method_output_stream_blocking_splice(wasi_io_streams_borrow_output_stream_t self, wasi_io_streams_borrow_input_stream_t src, uint64_t len, uint64_t *ret, wasi_io_streams_stream_error_t *err);

// Imported Functions from `wasi:http/types@0.2.0`
// Construct an empty HTTP Fields.
// 
// The resulting `fields` is mutable.
extern wasi_http_types_own_fields_t wasi_http_types_constructor_fields(void);
// Construct an HTTP Fields.
// 
// The resulting `fields` is mutable.
// 
// The list represents each key-value pair in the Fields. Keys
// which have multiple values are represented by multiple entries in this
// list with the same key.
// 
// The tuple is a pair of the field key, represented as a string, and
// Value, represented as a list of bytes. In a valid Fields, all keys
// and values are valid UTF-8 strings. However, values are not always
// well-formed, so they are represented as a raw list of bytes.
// 
// An error result will be returned if any header or value was
// syntactically invalid, or if a header was forbidden.
extern bool wasi_http_types_static_fields_from_list(hello_list_tuple2_field_key_field_value_t *entries, wasi_http_types_own_fields_t *ret, wasi_http_types_header_error_t *err);
// Get all of the values corresponding to a key. If the key is not present
// in this `fields`, an empty list is returned. However, if the key is
// present but empty, this is represented by a list with one or more
// empty field-values present.
extern void wasi_http_types_method_fields_get(wasi_http_types_borrow_fields_t self, wasi_http_types_field_key_t *name, hello_list_field_value_t *ret);
// Returns `true` when the key is present in this `fields`. If the key is
// syntactically invalid, `false` is returned.
extern bool wasi_http_types_method_fields_has(wasi_http_types_borrow_fields_t self, wasi_http_types_field_key_t *name);
// Set all of the values for a key. Clears any existing values for that
// key, if they have been set.
// 
// Fails with `header-error.immutable` if the `fields` are immutable.
extern bool wasi_http_types_method_fields_set(wasi_http_types_borrow_fields_t self, wasi_http_types_field_key_t *name, hello_list_field_value_t *value, wasi_http_types_header_error_t *err);
// Delete all values for a key. Does nothing if no values for the key
// exist.
// 
// Fails with `header-error.immutable` if the `fields` are immutable.
extern bool wasi_http_types_method_fields_delete(wasi_http_types_borrow_fields_t self, wasi_http_types_field_key_t *name, wasi_http_types_header_error_t *err);
// Append a value for a key. Does not change or delete any existing
// values for that key.
// 
// Fails with `header-error.immutable` if the `fields` are immutable.
extern bool wasi_http_types_method_fields_append(wasi_http_types_borrow_fields_t self, wasi_http_types_field_key_t *name, wasi_http_types_field_value_t *value, wasi_http_types_header_error_t *err);
// Retrieve the full set of keys and values in the Fields. Like the
// constructor, the list represents each key-value pair.
// 
// The outer list represents each key-value pair in the Fields. Keys
// which have multiple values are represented by multiple entries in this
// list with the same key.
extern void wasi_http_types_method_fields_entries(wasi_http_types_borrow_fields_t self, hello_list_tuple2_field_key_field_value_t *ret);
// Make a deep copy of the Fields. Equivelant in behavior to calling the
// `fields` constructor on the return value of `entries`. The resulting
// `fields` is mutable.
extern wasi_http_types_own_fields_t wasi_http_types_method_fields_clone(wasi_http_types_borrow_fields_t self);
// Returns the method of the incoming request.
extern void wasi_http_types_method_incoming_request_method(wasi_http_types_borrow_incoming_request_t self, wasi_http_types_method_t *ret);
// Returns the path with query parameters from the request, as a string.
extern bool wasi_http_types_method_incoming_request_path_with_query(wasi_http_types_borrow_incoming_request_t self, hello_string_t *ret);
// Returns the protocol scheme from the request.
extern bool wasi_http_types_method_incoming_request_scheme(wasi_http_types_borrow_incoming_request_t self, wasi_http_types_scheme_t *ret);
// Returns the authority from the request, if it was present.
extern bool wasi_http_types_method_incoming_request_authority(wasi_http_types_borrow_incoming_request_t self, hello_string_t *ret);
// Get the `headers` associated with the request.
// 
// The returned `headers` resource is immutable: `set`, `append`, and
// `delete` operations will fail with `header-error.immutable`.
// 
// The `headers` returned are a child resource: it must be dropped before
// the parent `incoming-request` is dropped. Dropping this
// `incoming-request` before all children are dropped will trap.
extern wasi_http_types_own_headers_t wasi_http_types_method_incoming_request_headers(wasi_http_types_borrow_incoming_request_t self);
// Gives the `incoming-body` associated with this request. Will only
// return success at most once, and subsequent calls will return error.
extern bool wasi_http_types_method_incoming_request_consume(wasi_http_types_borrow_incoming_request_t self, wasi_http_types_own_incoming_body_t *ret);
// Construct a new `outgoing-request` with a default `method` of `GET`, and
// `none` values for `path-with-query`, `scheme`, and `authority`.
// 
// * `headers` is the HTTP Headers for the Request.
// 
// It is possible to construct, or manipulate with the accessor functions
// below, an `outgoing-request` with an invalid combination of `scheme`
// and `authority`, or `headers` which are not permitted to be sent.
// It is the obligation of the `outgoing-handler.handle` implementation
// to reject invalid constructions of `outgoing-request`.
extern wasi_http_types_own_outgoing_request_t wasi_http_types_constructor_outgoing_request(wasi_http_types_own_headers_t headers);
// Returns the resource corresponding to the outgoing Body for this
// Request.
// 
// Returns success on the first call: the `outgoing-body` resource for
// this `outgoing-request` can be retrieved at most once. Subsequent
// calls will return error.
extern bool wasi_http_types_method_outgoing_request_body(wasi_http_types_borrow_outgoing_request_t self, wasi_http_types_own_outgoing_body_t *ret);
// Get the Method for the Request.
extern void wasi_http_types_method_outgoing_request_method(wasi_http_types_borrow_outgoing_request_t self, wasi_http_types_method_t *ret);
// Set the Method for the Request. Fails if the string present in a
// `method.other` argument is not a syntactically valid method.
extern bool wasi_http_types_method_outgoing_request_set_method(wasi_http_types_borrow_outgoing_request_t self, wasi_http_types_method_t *method);
// Get the combination of the HTTP Path and Query for the Request.
// When `none`, this represents an empty Path and empty Query.
extern bool wasi_http_types_method_outgoing_request_path_with_query(wasi_http_types_borrow_outgoing_request_t self, hello_string_t *ret);
// Set the combination of the HTTP Path and Query for the Request.
// When `none`, this represents an empty Path and empty Query. Fails is the
// string given is not a syntactically valid path and query uri component.
extern bool wasi_http_types_method_outgoing_request_set_path_with_query(wasi_http_types_borrow_outgoing_request_t self, hello_string_t *maybe_path_with_query);
// Get the HTTP Related Scheme for the Request. When `none`, the
// implementation may choose an appropriate default scheme.
extern bool wasi_http_types_method_outgoing_request_scheme(wasi_http_types_borrow_outgoing_request_t self, wasi_http_types_scheme_t *ret);
// Set the HTTP Related Scheme for the Request. When `none`, the
// implementation may choose an appropriate default scheme. Fails if the
// string given is not a syntactically valid uri scheme.
extern bool wasi_http_types_method_outgoing_request_set_scheme(wasi_http_types_borrow_outgoing_request_t self, wasi_http_types_scheme_t *maybe_scheme);
// Get the HTTP Authority for the Request. A value of `none` may be used
// with Related Schemes which do not require an Authority. The HTTP and
// HTTPS schemes always require an authority.
extern bool wasi_http_types_method_outgoing_request_authority(wasi_http_types_borrow_outgoing_request_t self, hello_string_t *ret);
// Set the HTTP Authority for the Request. A value of `none` may be used
// with Related Schemes which do not require an Authority. The HTTP and
// HTTPS schemes always require an authority. Fails if the string given is
// not a syntactically valid uri authority.
extern bool wasi_http_types_method_outgoing_request_set_authority(wasi_http_types_borrow_outgoing_request_t self, hello_string_t *maybe_authority);
// Get the headers associated with the Request.
// 
// The returned `headers` resource is immutable: `set`, `append`, and
// `delete` operations will fail with `header-error.immutable`.
// 
// This headers resource is a child: it must be dropped before the parent
// `outgoing-request` is dropped, or its ownership is transfered to
// another component by e.g. `outgoing-handler.handle`.
extern wasi_http_types_own_headers_t wasi_http_types_method_outgoing_request_headers(wasi_http_types_borrow_outgoing_request_t self);
// Construct a default `request-options` value.
extern wasi_http_types_own_request_options_t wasi_http_types_constructor_request_options(void);
// The timeout for the initial connect to the HTTP Server.
extern bool wasi_http_types_method_request_options_connect_timeout(wasi_http_types_borrow_request_options_t self, wasi_http_types_duration_t *ret);
// Set the timeout for the initial connect to the HTTP Server. An error
// return value indicates that this timeout is not supported.
extern bool wasi_http_types_method_request_options_set_connect_timeout(wasi_http_types_borrow_request_options_t self, wasi_http_types_duration_t *maybe_duration);
// The timeout for receiving the first byte of the Response body.
extern bool wasi_http_types_method_request_options_first_byte_timeout(wasi_http_types_borrow_request_options_t self, wasi_http_types_duration_t *ret);
// Set the timeout for receiving the first byte of the Response body. An
// error return value indicates that this timeout is not supported.
extern bool wasi_http_types_method_request_options_set_first_byte_timeout(wasi_http_types_borrow_request_options_t self, wasi_http_types_duration_t *maybe_duration);
// The timeout for receiving subsequent chunks of bytes in the Response
// body stream.
extern bool wasi_http_types_method_request_options_between_bytes_timeout(wasi_http_types_borrow_request_options_t self, wasi_http_types_duration_t *ret);
// Set the timeout for receiving subsequent chunks of bytes in the Response
// body stream. An error return value indicates that this timeout is not
// supported.
extern bool wasi_http_types_method_request_options_set_between_bytes_timeout(wasi_http_types_borrow_request_options_t self, wasi_http_types_duration_t *maybe_duration);
// Set the value of the `response-outparam` to either send a response,
// or indicate an error.
// 
// This method consumes the `response-outparam` to ensure that it is
// called at most once. If it is never called, the implementation
// will respond with an error.
// 
// The user may provide an `error` to `response` to allow the
// implementation determine how to respond with an HTTP error response.
extern void wasi_http_types_static_response_outparam_set(wasi_http_types_own_response_outparam_t param, wasi_http_types_result_own_outgoing_response_error_code_t *response);
// Returns the status code from the incoming response.
extern wasi_http_types_status_code_t wasi_http_types_method_incoming_response_status(wasi_http_types_borrow_incoming_response_t self);
// Returns the headers from the incoming response.
// 
// The returned `headers` resource is immutable: `set`, `append`, and
// `delete` operations will fail with `header-error.immutable`.
// 
// This headers resource is a child: it must be dropped before the parent
// `incoming-response` is dropped.
extern wasi_http_types_own_headers_t wasi_http_types_method_incoming_response_headers(wasi_http_types_borrow_incoming_response_t self);
// Returns the incoming body. May be called at most once. Returns error
// if called additional times.
extern bool wasi_http_types_method_incoming_response_consume(wasi_http_types_borrow_incoming_response_t self, wasi_http_types_own_incoming_body_t *ret);
// Returns the contents of the body, as a stream of bytes.
// 
// Returns success on first call: the stream representing the contents
// can be retrieved at most once. Subsequent calls will return error.
// 
// The returned `input-stream` resource is a child: it must be dropped
// before the parent `incoming-body` is dropped, or consumed by
// `incoming-body.finish`.
// 
// This invariant ensures that the implementation can determine whether
// the user is consuming the contents of the body, waiting on the
// `future-trailers` to be ready, or neither. This allows for network
// backpressure is to be applied when the user is consuming the body,
// and for that backpressure to not inhibit delivery of the trailers if
// the user does not read the entire body.
extern bool wasi_http_types_method_incoming_body_stream(wasi_http_types_borrow_incoming_body_t self, wasi_http_types_own_input_stream_t *ret);
// Takes ownership of `incoming-body`, and returns a `future-trailers`.
// This function will trap if the `input-stream` child is still alive.
extern wasi_http_types_own_future_trailers_t wasi_http_types_static_incoming_body_finish(wasi_http_types_own_incoming_body_t this_);
// Returns a pollable which becomes ready when either the trailers have
// been received, or an error has occured. When this pollable is ready,
// the `get` method will return `some`.
extern wasi_http_types_own_pollable_t wasi_http_types_method_future_trailers_subscribe(wasi_http_types_borrow_future_trailers_t self);
// Returns the contents of the trailers, or an error which occured,
// once the future is ready.
// 
// The outer `option` represents future readiness. Users can wait on this
// `option` to become `some` using the `subscribe` method.
// 
// The outer `result` is used to retrieve the trailers or error at most
// once. It will be success on the first call in which the outer option
// is `some`, and error on subsequent calls.
// 
// The inner `result` represents that either the HTTP Request or Response
// body, as well as any trailers, were received successfully, or that an
// error occured receiving them. The optional `trailers` indicates whether
// or not trailers were present in the body.
// 
// When some `trailers` are returned by this method, the `trailers`
// resource is immutable, and a child. Use of the `set`, `append`, or
// `delete` methods will return an error, and the resource must be
// dropped before the parent `future-trailers` is dropped.
extern bool wasi_http_types_method_future_trailers_get(wasi_http_types_borrow_future_trailers_t self, wasi_http_types_result_result_option_own_trailers_error_code_void_t *ret);
// Construct an `outgoing-response`, with a default `status-code` of `200`.
// If a different `status-code` is needed, it must be set via the
// `set-status-code` method.
// 
// * `headers` is the HTTP Headers for the Response.
extern wasi_http_types_own_outgoing_response_t wasi_http_types_constructor_outgoing_response(wasi_http_types_own_headers_t headers);
// Get the HTTP Status Code for the Response.
extern wasi_http_types_status_code_t wasi_http_types_method_outgoing_response_status_code(wasi_http_types_borrow_outgoing_response_t self);
// Set the HTTP Status Code for the Response. Fails if the status-code
// given is not a valid http status code.
extern bool wasi_http_types_method_outgoing_response_set_status_code(wasi_http_types_borrow_outgoing_response_t self, wasi_http_types_status_code_t status_code);
// Get the headers associated with the Request.
// 
// The returned `headers` resource is immutable: `set`, `append`, and
// `delete` operations will fail with `header-error.immutable`.
// 
// This headers resource is a child: it must be dropped before the parent
// `outgoing-request` is dropped, or its ownership is transfered to
// another component by e.g. `outgoing-handler.handle`.
extern wasi_http_types_own_headers_t wasi_http_types_method_outgoing_response_headers(wasi_http_types_borrow_outgoing_response_t self);
// Returns the resource corresponding to the outgoing Body for this Response.
// 
// Returns success on the first call: the `outgoing-body` resource for
// this `outgoing-response` can be retrieved at most once. Subsequent
// calls will return error.
extern bool wasi_http_types_method_outgoing_response_body(wasi_http_types_borrow_outgoing_response_t self, wasi_http_types_own_outgoing_body_t *ret);
// Returns a stream for writing the body contents.
// 
// The returned `output-stream` is a child resource: it must be dropped
// before the parent `outgoing-body` resource is dropped (or finished),
// otherwise the `outgoing-body` drop or `finish` will trap.
// 
// Returns success on the first call: the `output-stream` resource for
// this `outgoing-body` may be retrieved at most once. Subsequent calls
// will return error.
extern bool wasi_http_types_method_outgoing_body_write(wasi_http_types_borrow_outgoing_body_t self, wasi_http_types_own_output_stream_t *ret);
// Finalize an outgoing body, optionally providing trailers. This must be
// called to signal that the response is complete. If the `outgoing-body`
// is dropped without calling `outgoing-body.finalize`, the implementation
// should treat the body as corrupted.
// 
// Fails if the body's `outgoing-request` or `outgoing-response` was
// constructed with a Content-Length header, and the contents written
// to the body (via `write`) does not match the value given in the
// Content-Length.
extern bool wasi_http_types_static_outgoing_body_finish(wasi_http_types_own_outgoing_body_t this_, wasi_http_types_own_trailers_t *maybe_trailers, wasi_http_types_error_code_t *err);
// Returns a pollable which becomes ready when either the Response has
// been received, or an error has occured. When this pollable is ready,
// the `get` method will return `some`.
extern wasi_http_types_own_pollable_t wasi_http_types_method_future_incoming_response_subscribe(wasi_http_types_borrow_future_incoming_response_t self);
// Returns the incoming HTTP Response, or an error, once one is ready.
// 
// The outer `option` represents future readiness. Users can wait on this
// `option` to become `some` using the `subscribe` method.
// 
// The outer `result` is used to retrieve the response or error at most
// once. It will be success on the first call in which the outer option
// is `some`, and error on subsequent calls.
// 
// The inner `result` represents that either the incoming HTTP Response
// status and headers have recieved successfully, or that an error
// occured. Errors may also occur while consuming the response body,
// but those will be reported by the `incoming-body` and its
// `output-stream` child.
extern bool wasi_http_types_method_future_incoming_response_get(wasi_http_types_borrow_future_incoming_response_t self, wasi_http_types_result_result_own_incoming_response_error_code_void_t *ret);
// Attempts to extract a http-related `error` from the wasi:io `error`
// provided.
// 
// Stream operations which return
// `wasi:io/stream/stream-error::last-operation-failed` have a payload of
// type `wasi:io/error/error` with more information about the operation
// that failed. This payload can be passed through to this function to see
// if there's http-related information about the error to return.
// 
// Note that this function is fallible because not all io-errors are
// http-related errors.
extern bool wasi_http_types_http_error_code(wasi_http_types_borrow_io_error_t err_, wasi_http_types_error_code_t *ret);

// Exported Functions from `wasi:http/incoming-handler@0.2.0`
void exports_wasi_http_incoming_handler_handle(exports_wasi_http_incoming_handler_own_incoming_request_t request, exports_wasi_http_incoming_handler_own_response_outparam_t response_out);

// Helper Functions

extern void wasi_io_poll_pollable_drop_own(wasi_io_poll_own_pollable_t handle);

extern void wasi_io_poll_pollable_drop_borrow(wasi_io_poll_borrow_pollable_t handle);

extern wasi_io_poll_borrow_pollable_t wasi_io_poll_borrow_pollable(wasi_io_poll_own_pollable_t handle);

void wasi_io_poll_list_borrow_pollable_free(wasi_io_poll_list_borrow_pollable_t *ptr);

void hello_list_u32_free(hello_list_u32_t *ptr);

extern void wasi_io_error_error_drop_own(wasi_io_error_own_error_t handle);

extern void wasi_io_error_error_drop_borrow(wasi_io_error_borrow_error_t handle);

extern wasi_io_error_borrow_error_t wasi_io_error_borrow_error(wasi_io_error_own_error_t handle);

void wasi_io_streams_stream_error_free(wasi_io_streams_stream_error_t *ptr);

extern void wasi_io_streams_input_stream_drop_own(wasi_io_streams_own_input_stream_t handle);

extern void wasi_io_streams_input_stream_drop_borrow(wasi_io_streams_borrow_input_stream_t handle);

extern wasi_io_streams_borrow_input_stream_t wasi_io_streams_borrow_input_stream(wasi_io_streams_own_input_stream_t handle);

extern void wasi_io_streams_output_stream_drop_own(wasi_io_streams_own_output_stream_t handle);

extern void wasi_io_streams_output_stream_drop_borrow(wasi_io_streams_borrow_output_stream_t handle);

extern wasi_io_streams_borrow_output_stream_t wasi_io_streams_borrow_output_stream(wasi_io_streams_own_output_stream_t handle);

void hello_list_u8_free(hello_list_u8_t *ptr);

void wasi_io_streams_result_list_u8_stream_error_free(wasi_io_streams_result_list_u8_stream_error_t *ptr);

void wasi_io_streams_result_u64_stream_error_free(wasi_io_streams_result_u64_stream_error_t *ptr);

void wasi_io_streams_result_void_stream_error_free(wasi_io_streams_result_void_stream_error_t *ptr);

void wasi_http_types_method_free(wasi_http_types_method_t *ptr);

void wasi_http_types_scheme_free(wasi_http_types_scheme_t *ptr);

void hello_option_string_free(hello_option_string_t *ptr);

void hello_option_u16_free(hello_option_u16_t *ptr);

void wasi_http_types_dns_error_payload_free(wasi_http_types_dns_error_payload_t *ptr);

void hello_option_u8_free(hello_option_u8_t *ptr);

void wasi_http_types_tls_alert_received_payload_free(wasi_http_types_tls_alert_received_payload_t *ptr);

void hello_option_u32_free(hello_option_u32_t *ptr);

void wasi_http_types_field_size_payload_free(wasi_http_types_field_size_payload_t *ptr);

void hello_option_u64_free(hello_option_u64_t *ptr);

void wasi_http_types_option_field_size_payload_free(wasi_http_types_option_field_size_payload_t *ptr);

void wasi_http_types_error_code_free(wasi_http_types_error_code_t *ptr);

void wasi_http_types_header_error_free(wasi_http_types_header_error_t *ptr);

void wasi_http_types_field_key_free(wasi_http_types_field_key_t *ptr);

void wasi_http_types_field_value_free(wasi_http_types_field_value_t *ptr);

extern void wasi_http_types_fields_drop_own(wasi_http_types_own_fields_t handle);

extern void wasi_http_types_fields_drop_borrow(wasi_http_types_borrow_fields_t handle);

extern wasi_http_types_borrow_fields_t wasi_http_types_borrow_fields(wasi_http_types_own_fields_t handle);

extern void wasi_http_types_incoming_request_drop_own(wasi_http_types_own_incoming_request_t handle);

extern void wasi_http_types_incoming_request_drop_borrow(wasi_http_types_borrow_incoming_request_t handle);

extern wasi_http_types_borrow_incoming_request_t wasi_http_types_borrow_incoming_request(wasi_http_types_own_incoming_request_t handle);

extern void wasi_http_types_outgoing_request_drop_own(wasi_http_types_own_outgoing_request_t handle);

extern void wasi_http_types_outgoing_request_drop_borrow(wasi_http_types_borrow_outgoing_request_t handle);

extern wasi_http_types_borrow_outgoing_request_t wasi_http_types_borrow_outgoing_request(wasi_http_types_own_outgoing_request_t handle);

extern void wasi_http_types_request_options_drop_own(wasi_http_types_own_request_options_t handle);

extern void wasi_http_types_request_options_drop_borrow(wasi_http_types_borrow_request_options_t handle);

extern wasi_http_types_borrow_request_options_t wasi_http_types_borrow_request_options(wasi_http_types_own_request_options_t handle);

extern void wasi_http_types_response_outparam_drop_own(wasi_http_types_own_response_outparam_t handle);

extern void wasi_http_types_response_outparam_drop_borrow(wasi_http_types_borrow_response_outparam_t handle);

extern wasi_http_types_borrow_response_outparam_t wasi_http_types_borrow_response_outparam(wasi_http_types_own_response_outparam_t handle);

extern void wasi_http_types_incoming_response_drop_own(wasi_http_types_own_incoming_response_t handle);

extern void wasi_http_types_incoming_response_drop_borrow(wasi_http_types_borrow_incoming_response_t handle);

extern wasi_http_types_borrow_incoming_response_t wasi_http_types_borrow_incoming_response(wasi_http_types_own_incoming_response_t handle);

extern void wasi_http_types_incoming_body_drop_own(wasi_http_types_own_incoming_body_t handle);

extern void wasi_http_types_incoming_body_drop_borrow(wasi_http_types_borrow_incoming_body_t handle);

extern wasi_http_types_borrow_incoming_body_t wasi_http_types_borrow_incoming_body(wasi_http_types_own_incoming_body_t handle);

extern void wasi_http_types_future_trailers_drop_own(wasi_http_types_own_future_trailers_t handle);

extern void wasi_http_types_future_trailers_drop_borrow(wasi_http_types_borrow_future_trailers_t handle);

extern wasi_http_types_borrow_future_trailers_t wasi_http_types_borrow_future_trailers(wasi_http_types_own_future_trailers_t handle);

extern void wasi_http_types_outgoing_response_drop_own(wasi_http_types_own_outgoing_response_t handle);

extern void wasi_http_types_outgoing_response_drop_borrow(wasi_http_types_borrow_outgoing_response_t handle);

extern wasi_http_types_borrow_outgoing_response_t wasi_http_types_borrow_outgoing_response(wasi_http_types_own_outgoing_response_t handle);

extern void wasi_http_types_outgoing_body_drop_own(wasi_http_types_own_outgoing_body_t handle);

extern void wasi_http_types_outgoing_body_drop_borrow(wasi_http_types_borrow_outgoing_body_t handle);

extern wasi_http_types_borrow_outgoing_body_t wasi_http_types_borrow_outgoing_body(wasi_http_types_own_outgoing_body_t handle);

extern void wasi_http_types_future_incoming_response_drop_own(wasi_http_types_own_future_incoming_response_t handle);

extern void wasi_http_types_future_incoming_response_drop_borrow(wasi_http_types_borrow_future_incoming_response_t handle);

extern wasi_http_types_borrow_future_incoming_response_t wasi_http_types_borrow_future_incoming_response(wasi_http_types_own_future_incoming_response_t handle);

void hello_tuple2_field_key_field_value_free(hello_tuple2_field_key_field_value_t *ptr);

void hello_list_tuple2_field_key_field_value_free(hello_list_tuple2_field_key_field_value_t *ptr);

void wasi_http_types_result_own_fields_header_error_free(wasi_http_types_result_own_fields_header_error_t *ptr);

void hello_list_field_value_free(hello_list_field_value_t *ptr);

void wasi_http_types_result_void_header_error_free(wasi_http_types_result_void_header_error_t *ptr);

void wasi_http_types_option_scheme_free(wasi_http_types_option_scheme_t *ptr);

void wasi_http_types_result_own_incoming_body_void_free(wasi_http_types_result_own_incoming_body_void_t *ptr);

void wasi_http_types_result_own_outgoing_body_void_free(wasi_http_types_result_own_outgoing_body_void_t *ptr);

void wasi_http_types_result_void_void_free(wasi_http_types_result_void_void_t *ptr);

void hello_option_duration_free(hello_option_duration_t *ptr);

void wasi_http_types_result_own_outgoing_response_error_code_free(wasi_http_types_result_own_outgoing_response_error_code_t *ptr);

void wasi_http_types_result_own_input_stream_void_free(wasi_http_types_result_own_input_stream_void_t *ptr);

void wasi_http_types_option_own_trailers_free(wasi_http_types_option_own_trailers_t *ptr);

void wasi_http_types_result_option_own_trailers_error_code_free(wasi_http_types_result_option_own_trailers_error_code_t *ptr);

void wasi_http_types_result_result_option_own_trailers_error_code_void_free(wasi_http_types_result_result_option_own_trailers_error_code_void_t *ptr);

void wasi_http_types_option_result_result_option_own_trailers_error_code_void_free(wasi_http_types_option_result_result_option_own_trailers_error_code_void_t *ptr);

void wasi_http_types_result_own_output_stream_void_free(wasi_http_types_result_own_output_stream_void_t *ptr);

void wasi_http_types_result_void_error_code_free(wasi_http_types_result_void_error_code_t *ptr);

void wasi_http_types_result_own_incoming_response_error_code_free(wasi_http_types_result_own_incoming_response_error_code_t *ptr);

void wasi_http_types_result_result_own_incoming_response_error_code_void_free(wasi_http_types_result_result_own_incoming_response_error_code_void_t *ptr);

void wasi_http_types_option_result_result_own_incoming_response_error_code_void_free(wasi_http_types_option_result_result_own_incoming_response_error_code_void_t *ptr);

void wasi_http_types_option_error_code_free(wasi_http_types_option_error_code_t *ptr);

// Transfers ownership of `s` into the string `ret`
void hello_string_set(hello_string_t *ret, const char*s);

// Creates a copy of the input nul-terminate string `s` and
// stores it into the component model string `ret`.
void hello_string_dup(hello_string_t *ret, const char*s);

// Deallocates the string pointed to by `ret`, deallocating
// the memory behind the string.
void hello_string_free(hello_string_t *ret);

#ifdef __cplusplus
}
#endif
#endif
