package wasmcloud:host@1.0.0;

world interfaces {
    import wasmcloud:bus/lattice@1.0.0;

    import wasi:blobstore/blobstore@0.2.0-draft;
    import wasi:config/runtime@0.2.0-draft;
    import wasi:http/outgoing-handler@0.2.0;
    import wasi:keyvalue/atomic@0.2.0-draft;
    import wasi:keyvalue/eventual@0.2.0-draft;
    import wasi:logging/logging;

    import wasmcloud:messaging/consumer;
}
