interface host {
    host-call: func(binding: string, namespace: string, operation: string, payload: option<list<u8>>) -> result<option<list<u8>>, string>
}

interface actor {
    guest-call: func(operation: string, payload: option<list<u8>>) -> result<option<list<u8>>, string>
}

default world wasmcloud {
    import wasi-stderr: pkg.wasi-stderr
    import wasi-io: pkg.wasi-io
    import wasi-filesystem: pkg.wasi-filesystem
    import wasi-exit: pkg.wasi-exit
    import wasi-environment: pkg.wasi-environment

    import host: self.host
    export actor: self.actor
}
