use std::path::PathBuf;
use std::sync::Arc;
use std::time::Duration;

use crate::component_source::{ComponentSource, LoadedComponent};
use crate::host::{Host, HostApi, HostConfig, WorkloadReservation};
use crate::oci::{self, OciConfig};
use crate::plugin::HostPlugin;
use anyhow::{Context as _, anyhow};
use futures::StreamExt as _;
use tokio::sync::oneshot;
use tracing::{debug, error, info, instrument, warn};

pub const HOST_API_PREFIX: &str = "runtime.host";
pub const OPERATOR_API_PREFIX: &str = "runtime.operator";
const HEARTBEAT_INTERVAL: Duration = Duration::from_secs(15);

/// How long the command loop may go quiet before it counts as stopped rather
/// than slow.
///
/// Three of whatever interval the host actually heartbeats on: the loop turns
/// at least once per interval, and a restart costs every workload on the host,
/// so this must not fire on one that is merely behind.
pub fn liveness_silence(heartbeat_interval: Duration) -> Duration {
    heartbeat_interval * 3
}
/// Most `workload.start` requests a host pulls and compiles at once, however
/// many cores it has. Past this the images held in memory cost more than the
/// extra parallelism buys.
const MAX_CONCURRENT_STARTS: usize = 4;
/// How long shutdown waits for in-flight commands before abandoning them.
///
/// A start stalled on an unreachable registry runs to its own pull timeout, and
/// waiting all of them out would hold shutdown for minutes — past the grace
/// period a terminating pod gets, so it is killed before `host.stop()` unbinds
/// anything. Better to abandon them and stop the host, which unbinds whatever
/// they had bound anyway.
pub const COMMAND_DRAIN_TIMEOUT: Duration = Duration::from_secs(5);

/// How long an aborted command is given to unwind before the host stops
/// regardless.
///
/// Separate from, and shorter than, [`COMMAND_DRAIN_TIMEOUT`]: that one waits
/// for commands to *finish*, this one only for already-aborted ones to reach an
/// await and let go. Together they bound the whole shutdown, which has to fit
/// inside the pod's termination grace period with room left for
/// `Host::stop` to unbind the plugins.
pub const COMMAND_ABORT_TIMEOUT: Duration = Duration::from_secs(2);

/// How many starts a host runs at once when nothing sets it.
///
/// Each permitted start ends in a Cranelift compile, and one compile spreads
/// itself over rayon's pool, so a permit is a floor on the cores it takes for
/// as long as it runs, not a ceiling — the pool's own size is what bounds the
/// rest. `available_parallelism` reads the cgroup quota a container is limited to,
/// and one core is left out of the count: a host that cannot poll its HTTP
/// accept loop or drain its NATS socket while it compiles is one Kubernetes
/// restarts out from under its workloads.
fn default_max_concurrent_starts() -> usize {
    std::thread::available_parallelism().map_or(1, |cores| starts_for_cores(cores.get()))
}

/// [`default_max_concurrent_starts`] against a known core count.
fn starts_for_cores(cores: usize) -> usize {
    cores.saturating_sub(1).clamp(1, MAX_CONCURRENT_STARTS)
}

pub mod types {
    pub mod v2 {
        // Committed output of `cargo xtask generate-protos` — regenerate
        // after changing /proto/wasmcloud/runtime/v2.
        // Generated by [`tonic-prost-build`]
        include!("generated/wasmcloud.runtime.v2.rs");
        // Generated by [`pbjson-build`]
        include!("generated/wasmcloud.runtime.v2.serde.rs");
    }
}

#[derive(Default)]
pub struct ClusterHostBuilder {
    host_builder: crate::host::HostBuilder,
    nats_client: Option<Arc<async_nats::Client>>,
    host_group: Option<String>,
    host_name: Option<String>,
    environment: Option<String>,
    heartbeat_interval: Option<Duration>,
    cleanup_interval: Option<Duration>,
    cleanup_age: Option<Duration>,
    host_config: Option<HostConfig>,
    max_concurrent_starts: Option<usize>,
    liveness: Option<Arc<crate::host::probes::Liveness>>,
}

impl ClusterHostBuilder {
    /// The interval this host will actually heartbeat on, resolved.
    ///
    /// Public so a caller sizing a liveness bound reads the number the host was
    /// built with rather than restating a default that can move underneath it.
    pub fn heartbeat_interval(&self) -> Duration {
        self.heartbeat_interval.unwrap_or(HEARTBEAT_INTERVAL)
    }

    /// Beat `liveness` every time the command loop turns, so `/livez` answers
    /// from whether this host is still servicing its control plane rather than
    /// from whether a socket accepted.
    pub fn with_liveness(mut self, liveness: Arc<crate::host::probes::Liveness>) -> Self {
        self.liveness = Some(liveness);
        self
    }

    pub fn with_host_group(mut self, host_group: impl AsRef<str>) -> Self {
        self.host_group = Some(host_group.as_ref().into());
        self
    }

    pub fn with_host_name(mut self, host_name: impl AsRef<str>) -> Self {
        self.host_name = Some(host_name.as_ref().into());
        self
    }

    /// Sets the environment the host advertises in its heartbeat. For
    /// in-cluster host pods this is the pod's namespace (sourced from
    /// the downward API); for external hosts it is whatever identifier
    /// the operator wants to attribute the host to.
    pub fn with_environment(mut self, environment: impl AsRef<str>) -> Self {
        self.environment = Some(environment.as_ref().into());
        self
    }

    pub fn with_host_config(mut self, host_config: HostConfig) -> Self {
        self.host_config = Some(host_config);
        self
    }

    pub fn with_host_builder(mut self, host_builder: crate::host::HostBuilder) -> Self {
        self.host_builder = host_builder;
        self
    }

    pub fn with_nats_client(mut self, nats_client: Arc<async_nats::Client>) -> Self {
        self.nats_client = Some(nats_client);
        self
    }

    pub fn with_plugin<T: HostPlugin>(mut self, plugin: Arc<T>) -> anyhow::Result<Self> {
        self.host_builder = self.host_builder.with_plugin(plugin)?;
        Ok(self)
    }

    /// Sets the operator's plugin binding declarations. See
    /// [`crate::host::HostBuilder::with_plugin_bindings`].
    pub fn with_plugin_bindings(mut self, bindings: crate::plugin::PluginBindings) -> Self {
        self.host_builder = self.host_builder.with_plugin_bindings(bindings);
        self
    }

    /// Every native (non-component) plugin registered so far. See
    /// [`crate::host::HostBuilder::native_plugins`].
    #[cfg(feature = "host-component-plugins")]
    pub fn native_plugins(&self) -> std::collections::HashMap<&'static str, Arc<dyn HostPlugin>> {
        self.host_builder.native_plugins()
    }

    /// The HTTP handler registered so far, if any. See
    /// [`crate::host::HostBuilder::http_handler`].
    #[cfg(feature = "host-component-plugins")]
    pub fn http_handler(&self) -> Option<Arc<dyn crate::host::http::HostHandler>> {
        self.host_builder.http_handler()
    }

    /// Registers the multiplexed plugin set. See
    /// [`crate::host::HostBuilder::with_multiplexed_plugins`].
    #[cfg(feature = "wasm_component_model_implements")]
    pub fn with_multiplexed_plugins(mut self) -> anyhow::Result<Self> {
        self.host_builder = self.host_builder.with_multiplexed_plugins()?;
        Ok(self)
    }

    /// A zero frequency is read as unset and takes the default. Passing it on
    /// would panic `tokio::time::interval` inside the spawned task, where the
    /// host reports itself started and then serves nothing; clamping it to some
    /// tiny period instead trades that for the cleanup walking the OCI cache
    /// thousands of times a second, inline in the loop that serves requests.
    pub fn with_artifact_cleaner(mut self, frequency: Duration, max_age: Duration) -> Self {
        self.cleanup_interval = (!frequency.is_zero()).then_some(frequency);
        self.cleanup_age = Some(max_age);
        self
    }

    /// Sets how often the host publishes to `runtime.operator.heartbeat.{id}`.
    /// It has to stay well inside the operator's unreachable window, which
    /// deletes a host it has not heard from along with its workloads.
    /// Zero is read as unset and takes the default, for the same reason as
    /// [`ClusterHostBuilder::with_artifact_cleaner`].
    pub fn with_heartbeat_interval(mut self, interval: Duration) -> Self {
        self.heartbeat_interval = (!interval.is_zero()).then_some(interval);
        self
    }

    /// Caps how many `workload.start` requests this host serves at once,
    /// overriding [`default_max_concurrent_starts`].
    /// Zero is raised to one: a host that cannot start anything is not a host.
    pub fn with_max_concurrent_starts(mut self, starts: usize) -> Self {
        self.max_concurrent_starts = Some(starts.max(1));
        self
    }

    pub fn with_engine(mut self, engine: crate::engine::Engine) -> Self {
        self.host_builder = self.host_builder.with_engine(engine);
        self
    }

    pub fn with_meters(mut self, meters: crate::observability::Meters) -> Self {
        self.host_builder = self.host_builder.with_meters(meters);
        self
    }

    pub fn with_http_handler(
        mut self,
        http_handler: Arc<dyn crate::host::http::HostHandler>,
    ) -> Self {
        self.host_builder = self.host_builder.with_http_handler(http_handler);
        self
    }

    pub fn build(self) -> anyhow::Result<ClusterHost> {
        let Some(nats_client) = self.nats_client else {
            anyhow::bail!("nats_client is required");
        };
        let Some(host_group) = self.host_group else {
            anyhow::bail!("host_group is required");
        };

        let mut builder = self
            .host_builder
            .with_label("hostgroup", host_group.clone());

        if let Some(host_name) = self.host_name {
            builder = builder.with_hostname(host_name)
        }

        if let Some(environment) = self.environment {
            builder = builder.with_environment(environment);
        }

        if let Some(host_config) = self.host_config {
            builder = builder.with_config(host_config);
        }

        let heartbeat_interval = self.heartbeat_interval.unwrap_or(HEARTBEAT_INTERVAL);
        let host = builder.build()?;
        Ok(ClusterHost {
            prepared_host: host,
            nats_client,
            heartbeat_interval,
            cleanup_interval: self.cleanup_interval.unwrap_or(Duration::from_secs(300)),
            cleanup_age: self.cleanup_age.unwrap_or(Duration::from_secs(3600)),
            max_concurrent_starts: self
                .max_concurrent_starts
                .unwrap_or_else(default_max_concurrent_starts),
            liveness: self.liveness,
        })
    }
}

pub struct ClusterHost {
    prepared_host: Host,
    nats_client: Arc<async_nats::Client>,
    heartbeat_interval: Duration,
    cleanup_interval: Duration,
    cleanup_age: Duration,
    max_concurrent_starts: usize,
    liveness: Option<Arc<crate::host::probes::Liveness>>,
}

impl ClusterHost {
    pub fn host(&self) -> &Host {
        &self.prepared_host
    }

    /// Start the cluser host
    pub async fn start(
        self,
    ) -> anyhow::Result<(impl HostApi, impl Future<Output = anyhow::Result<()>>)> {
        let (one_shot_tx, mut one_shot_rx) = oneshot::channel();
        let nats_client = self.nats_client.clone();
        let host = self
            .prepared_host
            .start()
            .await
            .context("failed to start host")?;

        let heartbeat_interval = self.heartbeat_interval;
        let cleanup_interval = self.cleanup_interval;
        let max_concurrent_starts = self.max_concurrent_starts;
        let liveness = self.liveness.clone();
        let host_id = host.id().to_string();
        let host = host.clone();

        info!(
        host_id=?host_id,
        friendly_name=?host.friendly_name(),
        host_name=?host.hostname(),
        labels=?host.labels(),
        version=?host.version(),
        max_concurrent_starts,
        "Host started");

        host.log_interfaces();

        let task = tokio::task::spawn({
            let host = host.clone();
            async move {
                let host_subject = host_subject(host_id.as_ref());

                let heartbeat_subject = heartbeat_subject(host_id.as_ref());

                let mut api_subscription = nats_client
                    .subscribe(host_subject)
                    .await
                    .context("failed to subscribe for API requests")?;
                let mut heartbeat_timer = tokio::time::interval(heartbeat_interval);

                // Only `workload.start` waits on this permit; stops and status
                // never do, so neither queues behind a pull.
                let starts = Arc::new(tokio::sync::Semaphore::new(max_concurrent_starts));
                // Commands run as their own tasks, so shutdown has to wait for
                // them: `host.stop()` unbinds every plugin, and a start still
                // running past it would bind against stopped plugins and leave
                // a service nothing tears down.
                let mut commands = tokio::task::JoinSet::new();

                let mut oci_cleanup_timer = tokio::time::interval(cleanup_interval);

                loop {
                    // Every turn, whichever branch woke it. The heartbeat timer
                    // alone guarantees one per interval, so silence here means
                    // the loop itself has stopped — which is what `/livez`
                    // reports and the only thing worth a restart.
                    if let Some(liveness) = &liveness {
                        liveness.beat();
                    }
                    tokio::select! {
                        // Shutdown signal
                        _ = &mut one_shot_rx => {
                            if let Err(e) = api_subscription.unsubscribe().await {
                                error!("failed to unsubscribe from API requests: {e}");
                            }
                            // Anything still queued gives its workload id back
                            // and returns rather than starting something this
                            // host is about to tear down.
                            starts.close();
                            let drained = tokio::time::timeout(COMMAND_DRAIN_TIMEOUT, async {
                                while let Some(finished) = commands.join_next().await {
                                    if let Err(e) = finished {
                                        error!("command task failed during shutdown: {e}");
                                    }
                                }
                            })
                            .await;
                            if drained.is_err() {
                                warn!(
                                    "commands still running after {COMMAND_DRAIN_TIMEOUT:?}; \
                                     abandoning them to stop the host"
                                );
                                commands.abort_all();
                                // `abort_all` only asks. Wait for the tasks to
                                // reach their next await and unwind, or
                                // `host.stop()` unbinds plugins underneath one
                                // still binding them.
                                //
                                // Bounded: an aborted task cancels at its next
                                // await, and a command inside a synchronous
                                // compile has none. Waiting it out holds the
                                // shutdown past the pod's grace period, so
                                // `host.stop()` never runs at all.
                                let unwound = tokio::time::timeout(
                                    COMMAND_ABORT_TIMEOUT,
                                    async {
                                        while let Some(finished) = commands.join_next().await {
                                            // A panic while unwinding still
                                            // matters: the task may hold a
                                            // workload id it never released.
                                            if let Err(e) = finished
                                                && !e.is_cancelled()
                                            {
                                                error!("aborted command task failed: {e}");
                                            }
                                        }
                                    },
                                )
                                .await;
                                if unwound.is_err() {
                                    warn!(
                                        "commands still unwinding {COMMAND_ABORT_TIMEOUT:?} after \
                                         abort; stopping the host without them"
                                    );
                                }
                            }
                            return host.stop().await.context("failed to stop host");
                        }
                        // Reaps finished commands. A panicked one is fatal: it
                        // may have died holding a workload id it claimed and
                        // never committed or released, and no later stop can
                        // free that slot — the id would be refused as "already
                        // exists" for the life of the host. Taking the host
                        // down is what a panic here did before commands ran as
                        // their own tasks, and a restart is what clears it.
                        Some(finished) = commands.join_next() => {
                            if let Err(e) = finished {
                                return Err(anyhow!("command task failed: {e}"));
                            }
                        }
                        // OCI cache cleanup
                        _ = oci_cleanup_timer.tick() => {
                            if let Some(cache_dir) = host.config().oci_cache_dir.as_ref() &&
                            let Err(e) = oci::cleanup_cache(cache_dir, self.cleanup_age).await {
                                error!("error during OCI cache cleanup: {e}");
                            }
                        }
                        // Send heartbeat
                        _ = heartbeat_timer.tick() => {
                            // Returning here would drop `commands`, aborting
                            // in-flight starts after they have reserved their
                            // ids, and skip the `host.stop()` that unbinds
                            // their plugins. A missed heartbeat is worth none
                            // of that; the next tick tries again.
                            match host_heartbeat(&host).await.and_then(|heartbeat| {
                                serde_json::to_vec(&heartbeat).context("failed to serialize heartbeat")
                            }) {
                                Ok(heartbeat_bytes) => {
                                    if let Err(e) = nats_client
                                        .publish(heartbeat_subject.clone(), heartbeat_bytes.into())
                                        .await
                                    {
                                        error!("failed to publish heartbeat: {e}");
                                    }
                                }
                                Err(e) => error!("failed to build heartbeat: {e}"),
                            }
                        }
                        // Handle API requests
                        Some(msg) = api_subscription.next() => {
                            // `select!` runs one branch to completion, so a
                            // command awaited here would hold up the heartbeat
                            // above for as long as it takes to pull and compile.
                            // A host whose heartbeats stop looks unreachable to
                            // the operator, which deletes it and its workloads.
                            //
                            // Commands naming one workload are ordered by the
                            // host's reservation on that id, not by this loop:
                            // a start claims the id before it fetches anything,
                            // and a stop that finds the claim hands the teardown
                            // back to the start holding it.
                            let host = host.clone();
                            let nats_client = nats_client.clone();
                            let starts = Arc::clone(&starts);
                            commands.spawn(async move {
                                match handle_command(host.as_ref(), &msg, host.config(), &starts).await {
                                    Ok(resp_bytes) => {
                                        if let Some(reply_to) = msg.reply
                                            && let Err(e) = nats_client.publish(reply_to, resp_bytes.into()).await
                                        {
                                            error!("failed to publish API response: {e}");
                                        }
                                    }
                                    Err(e) => {
                                        error!("error handling command: {e}");
                                    }
                                }
                            });
                        }
                    }
                }
            }
        });

        Ok((host, async move {
            let _ = one_shot_tx.send(());
            task.await?
        }))
    }

    /// Run the cluster host, with no API access
    pub async fn run(self) -> anyhow::Result<impl Future<Output = anyhow::Result<()>>> {
        let (_host, cleanup) = self.start().await?;
        Ok(cleanup)
    }
}

pub async fn run_cluster_host(
    cluster_host: ClusterHost,
) -> anyhow::Result<impl Future<Output = anyhow::Result<()>>> {
    cluster_host.run().await
}

/// Configuration options for NATS connections
#[derive(Debug, Clone, Default)]
pub struct NatsConnectionOptions {
    /// Request timeout for NATS operations
    pub request_timeout: Option<Duration>,
    /// Path to TLS CA certificate file for NATS connection
    pub tls_ca: Option<PathBuf>,
    /// Enable TLS handshake first mode for NATS connection
    pub tls_first: bool,
    /// Path to NATS TLS certificate file
    pub tls_cert: Option<PathBuf>,
    /// Path to NATS TLS private key file
    pub tls_key: Option<PathBuf>,
}

#[instrument(skip_all)]
pub async fn connect_nats(
    addr: impl async_nats::ToServerAddrs,
    options: NatsConnectionOptions,
) -> Result<async_nats::Client, anyhow::Error> {
    let mut opts = async_nats::ConnectOptions::new();

    if let Some(timeout) = options.request_timeout {
        opts = opts.request_timeout(Some(timeout));
    }

    if let Some(ca_path) = options.tls_ca {
        opts = opts.add_root_certificates(ca_path)
    }

    if options.tls_first {
        opts = opts.tls_first();
    }

    if let (Some(cert_path), Some(key_path)) = (options.tls_cert, options.tls_key) {
        opts = opts.add_client_certificate(cert_path, key_path)
    }

    // Without a callback these events are raised and discarded. `SlowConsumer`
    // in particular is the *only* signal that a subscription's buffer
    // overflowed and messages were dropped — async-nats `try_send`s into that
    // buffer and drops silently on overflow, so an unobserved event means
    // core-NATS traffic disappearing from a host that otherwise looks healthy.
    opts = opts.event_callback(|event| async move {
        match event {
            async_nats::Event::SlowConsumer(sid) => tracing::warn!(
                subscription = sid,
                "NATS slow consumer: the subscription buffer overflowed and messages were \
                 dropped. The handler is not keeping up — check for saturated messaging \
                 admission (`messaging.admission.shed`) or slow handlers"
            ),
            async_nats::Event::Disconnected => {
                tracing::warn!("disconnected from NATS; buffered operations will be retried")
            }
            async_nats::Event::Connected => tracing::info!("connected to NATS"),
            async_nats::Event::ClientError(err) => tracing::warn!(%err, "NATS client error"),
            async_nats::Event::ServerError(err) => tracing::warn!(%err, "NATS server error"),
            other => tracing::debug!(event = %other, "NATS connection event"),
        }
    });

    opts.connect(addr)
        .await
        .context("failed to connect to NATS")
}

pub fn host_subject(host_id: &str) -> String {
    format!("{HOST_API_PREFIX}.{host_id}.>")
}

pub fn rpc_subject(host_id: &str, command: &str) -> String {
    format!("{HOST_API_PREFIX}.{host_id}.{command}")
}

pub fn heartbeat_subject(host_id: &str) -> String {
    format!("{OPERATOR_API_PREFIX}.heartbeat.{host_id}")
}

/// Helper function to serialize a message to the API format.
fn to_api<T: prost::Message + serde::Serialize>(msg: &T) -> Result<Vec<u8>, anyhow::Error> {
    serde_json::to_vec_pretty(msg).map_err(anyhow::Error::new)
}

/// Helper function to deserialize a message from the API format.
fn from_api<'de, T: serde::Deserialize<'de>>(bytes: &'de [u8]) -> Result<T, anyhow::Error> {
    serde_json::from_slice(bytes).map_err(anyhow::Error::new)
}

#[instrument(level = "debug", skip_all, fields(subject = %msg.subject))]
async fn handle_command(
    host: &(impl HostApi + WorkloadReservation),
    msg: &async_nats::Message,
    config: &HostConfig,
    starts: &tokio::sync::Semaphore,
) -> Result<Vec<u8>, anyhow::Error> {
    let command = msg.subject.split('.').skip(3).collect::<Vec<_>>().join(".");

    let payload = &msg.payload;

    match command.as_str() {
        "heartbeat" => {
            let res = host_heartbeat(host).await?;
            to_api(&res)
        }
        "workload.start" => {
            let req: types::v2::WorkloadStartRequest = from_api(payload)?;
            let res = workload_start(host, req, config, starts).await?;
            to_api(&res)
        }
        "workload.stop" => {
            let req: types::v2::WorkloadStopRequest = from_api(payload)?;
            let res = workload_stop(host, req).await?;
            to_api(&res)
        }
        "workload.status" => {
            let req: types::v2::WorkloadStatusRequest = from_api(payload)?;
            let res = workload_status(host, req).await?;
            to_api(&res)
        }
        // catch-all
        _ => anyhow::bail!("unknown command: {command}"),
    }
}

/// Convert ImagePullSecret from protobuf to OciConfig
fn image_pull_secret_to_oci_config(
    config: &HostConfig,
    pull_secret: &Option<types::v2::ImagePullSecret>,
) -> oci::OciConfig {
    let mut oci_config = match &pull_secret {
        Some(creds) => oci::OciConfig::new_with_credentials(&creds.username, &creds.password),
        None => OciConfig::default(),
    };
    oci_config.cache_dir = config.oci_cache_dir.clone();
    oci_config.insecure = config.allow_oci_insecure;
    oci_config.timeout = config.oci_pull_timeout;

    oci_config
}

/// Build the runtime's component from the one on the wire, once its image has
/// been pulled and its resources parsed.
///
/// Every field the wire carries has to land here: one dropped in this
/// conversion is unreachable from a deployed workload while looking wired
/// everywhere else. Split out from the pull loop so that stays true under test
/// without an image pull. The instance limits travel verbatim — the runtime
/// decodes them once, in [`crate::engine::InstancePolicy`].
fn component_from_wire(
    wire: &types::v2::Component,
    loaded: LoadedComponent,
    local_resources: crate::types::LocalResources,
) -> crate::types::Component {
    crate::types::Component {
        name: wire.name.clone(),
        bytes: loaded.bytes,
        digest: loaded.digest,
        local_resources,
        pool_size: wire.pool_size,
        max_invocations: wire.max_invocations,
        max_concurrency: wire.max_concurrency,
        reclaim_window_seconds: wire.reclaim_window_seconds,
        reclaim_min_instances: wire.reclaim_min_instances,
    }
}

#[instrument(level = "debug", skip_all)]
async fn host_heartbeat(host: &impl HostApi) -> anyhow::Result<types::v2::HostHeartbeat> {
    let hb = host.heartbeat().await?;

    Ok(hb.into())
}

/// A workload that could not be started, reported to the scheduler and to this
/// host's own log.
///
/// The response travels back to whoever asked, and nothing else here would say
/// why: an image the host cannot pull — a registry behind a CA it does not
/// trust, a reference that does not exist — otherwise leaves no trace on the
/// machine that failed to pull it.
fn workload_start_error(workload_id: &str, message: String) -> types::v2::WorkloadStartResponse {
    // `reason`, not `message`: `message` is the field tracing gives the event's
    // own text, and a second one under that name displaces it.
    error!(workload_id, reason = message, "failed to start workload");
    types::v2::WorkloadStartResponse {
        workload_status: Some(types::v2::WorkloadStatus {
            workload_id: workload_id.to_string(),
            workload_state: types::v2::WorkloadState::Error.into(),
            message,
        }),
    }
}

#[instrument(skip_all, fields(
    workload_id = %req.workload_id,
    workload.name=?req.workload.as_ref().map(|w| &w.name).unwrap_or(&"<none>".to_string()),
    workload.namespace=?req.workload.as_ref().map(|w| &w.namespace).unwrap_or(&"<none>".to_string())),
    )]
async fn workload_start(
    host: &impl WorkloadReservation,
    req: types::v2::WorkloadStartRequest,
    config: &HostConfig,
    starts: &tokio::sync::Semaphore,
) -> anyhow::Result<types::v2::WorkloadStartResponse> {
    let Some(types::v2::Workload {
        namespace,
        name,
        annotations,
        service,
        wit_world,
        volumes,
    }) = req.workload
    else {
        anyhow::bail!("workload is required");
    };

    let workload_id = req.workload_id.clone();
    if workload_id.is_empty() {
        anyhow::bail!("workload_id is required");
    }

    // Claimed before any image is fetched. Until the host holds the id a
    // status reports it missing and a stop reports it already gone, so a stop
    // arriving here would tell the operator the teardown is done while this
    // start goes on to run the workload.
    let reservation = match host.workload_reserve(&workload_id).await {
        Ok(reservation) => reservation,
        // Reported, not logged again: the host logs this refusal at `warn`
        // precisely because a scheduler replaying a start is not a malfunction,
        // and `workload_start_error` would raise the same event to `error`.
        Err(message) => {
            return Ok(types::v2::WorkloadStartResponse {
                workload_status: Some(types::v2::WorkloadStatus {
                    workload_id,
                    workload_state: types::v2::WorkloadState::Error.into(),
                    message,
                }),
            });
        }
    };

    // Queued with the id already claimed. Waiting for a permit is time like
    // any other in which a stop or a status has to find this workload.
    let _permit = match starts.acquire().await {
        Ok(permit) => permit,
        Err(e) => {
            host.workload_release(&workload_id, reservation).await;
            return Ok(workload_start_error(
                &workload_id,
                format!("host is no longer accepting starts: {e}"),
            ));
        }
    };

    // Every exit from here gives the id back, so a start that never began
    // cannot leave it reserved against the next one.
    let prepared = async {
        let (components, host_interfaces) = if let Some(wit_world) = wit_world {
            let mut pulled_components = Vec::with_capacity(wit_world.components.len());
            for component in &wit_world.components {
                let oci_config =
                    image_pull_secret_to_oci_config(config, &component.image_pull_secret);
                let source = ComponentSource::Oci {
                    image: component.image.clone(),
                    pull_policy: component.image_pull_policy().into(),
                };
                // `load` already names the reference it failed on; this says which
                // of the workload's components asked for it, so a multi-component
                // start reports something the operator can act on.
                let loaded = match source.load(oci_config).await.with_context(|| {
                    format!("failed to pull image for component '{}'", component.name)
                }) {
                    Ok(loaded) => loaded,
                    Err(e) => return Err(format!("{e:#}")),
                };
                let local_resources = match component.local_resources.clone() {
                    Some(lr) => match crate::types::LocalResources::try_from(lr) {
                        Ok(lr) => lr,
                        Err(e) => {
                            return Err(format!(
                                "invalid local_resources for component {}: {e:#}",
                                component.name
                            ));
                        }
                    },
                    None => crate::types::LocalResources::default(),
                };
                pulled_components.push(component_from_wire(component, loaded, local_resources))
            }
            (
                pulled_components,
                wit_world
                    .host_interfaces
                    .into_iter()
                    .map(Into::into)
                    .collect(),
            )
        } else {
            (vec![], vec![])
        };

        let service = if let Some(service) = service {
            let oci_config = image_pull_secret_to_oci_config(config, &service.image_pull_secret);
            let source = ComponentSource::Oci {
                image: service.image.clone(),
                pull_policy: service.image_pull_policy().into(),
            };
            // Distinguishes a service pull failure from a component one; both
            // otherwise report the same reference and cause.
            let loaded = match source
                .load(oci_config)
                .await
                .context("failed to pull image for the workload service")
            {
                Ok(loaded) => loaded,
                Err(e) => return Err(format!("{e:#}")),
            };
            let local_resources = match service.local_resources.clone() {
                Some(lr) => match crate::types::LocalResources::try_from(lr) {
                    Ok(lr) => lr,
                    Err(e) => {
                        return Err(format!("invalid local_resources for service: {e:#}"));
                    }
                },
                None => crate::types::LocalResources::default(),
            };
            Some(crate::types::Service {
                bytes: loaded.bytes,
                digest: loaded.digest,
                local_resources,
                max_restarts: service.max_restarts,
            })
        } else {
            None
        };

        let volumes = volumes.into_iter().map(Into::into).collect();

        let request = crate::types::WorkloadStartRequest {
            workload_id: workload_id.clone(),
            workload: crate::types::Workload {
                namespace,
                name,
                annotations,
                service,
                components,
                host_interfaces,
                volumes,
            },
        };
        Ok(request)
    }
    .await;

    let request = match prepared {
        Ok(request) => request,
        Err(message) => {
            host.workload_release(&workload_id, reservation).await;
            return Ok(workload_start_error(&workload_id, message));
        }
    };

    info!(
        workload_id=?workload_id,
        namespace=?request.workload.namespace,
        name=?request.workload.name,
        "Starting workload");

    Ok(host
        .workload_start_reserved(reservation, request)
        .await?
        .into())
}

#[instrument(skip_all, fields(workload_id = %req.workload_id))]
async fn workload_stop(
    host: &impl HostApi,
    req: types::v2::WorkloadStopRequest,
) -> anyhow::Result<types::v2::WorkloadStopResponse> {
    info!(
        workload_id=?req.workload_id,
        "Stopping workload");

    host.workload_stop(req.into()).await.map(|resp| resp.into())
}

#[instrument(skip_all, fields(workload_id = %req.workload_id))]
async fn workload_status(
    host: &impl HostApi,
    req: types::v2::WorkloadStatusRequest,
) -> anyhow::Result<types::v2::WorkloadStatusResponse> {
    debug!(
        workload_id=?req.workload_id,
        "Fetching workload status");

    host.workload_status(req.into())
        .await
        .map(|resp| resp.into())
}

impl From<types::v2::WitInterface> for crate::wit::WitInterface {
    fn from(wi: types::v2::WitInterface) -> Self {
        crate::wit::WitInterface {
            namespace: wi.namespace,
            package: wi.package,
            version: if wi.version.is_empty() {
                None
            } else {
                wi.version.parse::<semver::Version>().ok()
            },
            interfaces: wi.interfaces.into_iter().collect(),
            config: wi.config,
            name: if wi.name.is_empty() {
                None
            } else {
                Some(wi.name)
            },
        }
    }
}
impl From<types::v2::VolumeMount> for crate::types::VolumeMount {
    fn from(vm: types::v2::VolumeMount) -> Self {
        crate::types::VolumeMount {
            name: vm.name,
            mount_path: vm.mount_path,
            read_only: vm.read_only,
        }
    }
}

impl From<types::v2::Volume> for crate::types::Volume {
    fn from(v: types::v2::Volume) -> Self {
        crate::types::Volume {
            name: v.name,
            volume_type: match v.volume_type {
                Some(vt) => match vt {
                    types::v2::volume::VolumeType::HostPath(hp) => {
                        crate::types::VolumeType::HostPath(crate::types::HostPathVolume {
                            local_path: hp.local_path,
                        })
                    }
                    types::v2::volume::VolumeType::EmptyDir(_) => {
                        crate::types::VolumeType::EmptyDir(crate::types::EmptyDirVolume {})
                    }
                },
                None => crate::types::VolumeType::EmptyDir(crate::types::EmptyDirVolume {}),
            },
        }
    }
}

impl TryFrom<types::v2::LocalResources> for crate::types::LocalResources {
    type Error = anyhow::Error;

    fn try_from(lr: types::v2::LocalResources) -> Result<Self, Self::Error> {
        Ok(crate::types::LocalResources {
            memory_limit_mb: lr.memory_limit_mb,
            cpu_limit: lr.cpu_limit,
            config: lr.config,
            volume_mounts: lr.volume_mounts.into_iter().map(Into::into).collect(),
            allowed_hosts: parse_policy_entries(&lr.allowed_hosts, "allowed_hosts")?,
            environment: lr.environment,
            allowed_ip_name_lookups: parse_policy_entries(
                &lr.allowed_ip_name_lookups,
                "allowed_ip_name_lookups",
            )?,
            allowed_host_loopback_ports: parse_policy_entries(
                &lr.allowed_host_loopback_ports,
                "allowed_host_loopback_ports",
            )?,
        })
    }
}

/// Parses each entry of a policy list arriving from the wire, reporting
/// every bad entry at once.
///
/// A malformed entry fails the conversion so the workload start surfaces a
/// clear error rather than silently widening what the component may reach.
/// Failures are collected and joined into one message, rendered as a
/// heading line plus a bullet per bad entry, so a workload with several bad
/// entries doesn't have to be fixed one at a time.
fn parse_policy_entries<T>(entries: &[String], field: &str) -> anyhow::Result<Arc<[T]>>
where
    T: std::str::FromStr<Err = anyhow::Error>,
{
    let mut parsed: Vec<T> = Vec::with_capacity(entries.len());
    let mut errors: Vec<String> = Vec::new();
    for entry in entries {
        match entry.parse::<T>() {
            Ok(value) => parsed.push(value),
            Err(e) => errors.push(format!("'{entry}': {e:#}")),
        }
    }
    if !errors.is_empty() {
        return Err(anyhow!("invalid {field}:\n  - {}", errors.join("\n  - ")));
    }
    Ok(parsed.into())
}

impl From<crate::types::HostHeartbeat> for types::v2::HostHeartbeat {
    fn from(hb: crate::types::HostHeartbeat) -> Self {
        types::v2::HostHeartbeat {
            id: hb.id,
            hostname: hb.hostname,
            version: hb.version,
            started_at: Some(hb.started_at.into()),
            imports: hb.imports.into_iter().map(Into::into).collect(),
            exports: hb.exports.into_iter().map(Into::into).collect(),
            os_name: hb.os_name,
            os_arch: hb.os_arch,
            os_kernel: hb.os_kernel,
            system_cpu_usage: hb.system_cpu_usage,
            component_count: hb.component_count,
            workload_count: hb.workload_count,
            system_memory_total: hb.system_memory_total,
            system_memory_free: hb.system_memory_free,
            labels: hb.labels,
            friendly_name: hb.friendly_name,
            http_port: hb.http_port.into(),
            environment: hb.environment,
        }
    }
}

impl From<crate::wit::WitInterface> for types::v2::WitInterface {
    fn from(wi: crate::wit::WitInterface) -> Self {
        types::v2::WitInterface {
            namespace: wi.namespace,
            package: wi.package,
            version: wi.version.map(|v| v.to_string()).unwrap_or_default(),
            interfaces: wi.interfaces.into_iter().collect(),
            config: wi.config,
            name: wi.name.unwrap_or_default(),
        }
    }
}

// Conversions from API v2 request types to runtime::host types

impl From<types::v2::WorkloadStopRequest> for crate::types::WorkloadStopRequest {
    fn from(req: types::v2::WorkloadStopRequest) -> Self {
        crate::types::WorkloadStopRequest {
            workload_id: req.workload_id,
        }
    }
}

impl From<types::v2::WorkloadStatusRequest> for crate::types::WorkloadStatusRequest {
    fn from(req: types::v2::WorkloadStatusRequest) -> Self {
        crate::types::WorkloadStatusRequest {
            workload_id: req.workload_id,
        }
    }
}

// Conversions from runtime::host response types to API v2 types

impl From<crate::types::WorkloadStartResponse> for types::v2::WorkloadStartResponse {
    fn from(resp: crate::types::WorkloadStartResponse) -> Self {
        types::v2::WorkloadStartResponse {
            workload_status: Some(resp.workload_status.into()),
        }
    }
}

impl From<crate::types::WorkloadStopResponse> for types::v2::WorkloadStopResponse {
    fn from(resp: crate::types::WorkloadStopResponse) -> Self {
        types::v2::WorkloadStopResponse {
            workload_status: Some(resp.workload_status.into()),
        }
    }
}

impl From<crate::types::WorkloadStatusResponse> for types::v2::WorkloadStatusResponse {
    fn from(resp: crate::types::WorkloadStatusResponse) -> Self {
        types::v2::WorkloadStatusResponse {
            workload_status: Some(resp.workload_status.into()),
        }
    }
}

impl From<crate::types::WorkloadStatus> for types::v2::WorkloadStatus {
    fn from(status: crate::types::WorkloadStatus) -> Self {
        types::v2::WorkloadStatus {
            workload_id: status.workload_id,
            workload_state: status.workload_state as i32,
            message: status.message,
        }
    }
}

impl From<types::v2::ImagePullPolicy> for crate::oci::OciPullPolicy {
    fn from(policy: types::v2::ImagePullPolicy) -> Self {
        match policy {
            types::v2::ImagePullPolicy::Always => crate::oci::OciPullPolicy::Always,
            types::v2::ImagePullPolicy::IfNotPresent => crate::oci::OciPullPolicy::IfNotPresent,
            types::v2::ImagePullPolicy::Never => crate::oci::OciPullPolicy::Never,
            _ => crate::oci::OciPullPolicy::IfNotPresent,
        }
    }
}

#[cfg(test)]
mod tests {

    use super::*;
    use crate::host::allowed_hosts::AllowedHost;
    use crate::host::allowed_ip_name::AllowedIpName;

    /// A host always keeps a start it can run and a core it can serve on.
    #[test]
    fn starts_leave_a_core_to_serve_with() {
        assert_eq!(starts_for_cores(0), 1);
        assert_eq!(starts_for_cores(1), 1);
        assert_eq!(starts_for_cores(2), 1);
        assert_eq!(starts_for_cores(4), 3);
        assert_eq!(starts_for_cores(5), MAX_CONCURRENT_STARTS);
        assert_eq!(starts_for_cores(64), MAX_CONCURRENT_STARTS);
    }

    /// Every instance limit a component declares on the wire has to reach the
    /// runtime. An in-process test builds `types::Component` directly and so
    /// never crosses this conversion, which is where a limit that exists on
    /// both sides can go missing — leaving the knob unreachable from a
    /// workload deployed through the operator.
    #[test]
    fn wire_limits_reach_the_runtime() {
        let wire = types::v2::Component {
            name: "pooled".to_string(),
            pool_size: 4,
            max_invocations: 100,
            max_concurrency: 8,
            reclaim_window_seconds: 30,
            reclaim_min_instances: 2,
            ..Default::default()
        };

        let component = component_from_wire(
            &wire,
            LoadedComponent {
                bytes: b"\0asm".as_slice().into(),
                digest: Some("sha256:abc".to_string()),
            },
            crate::types::LocalResources::default(),
        );
        assert_eq!(component.name, "pooled");
        assert_eq!(component.digest.as_deref(), Some("sha256:abc"));
        assert_eq!(component.pool_size, 4);
        assert_eq!(component.max_invocations, 100);
        assert_eq!(component.max_concurrency, 8);
        assert_eq!(component.reclaim_window_seconds, 30);
        assert_eq!(component.reclaim_min_instances, 2);

        // And the runtime reads those limits as the policy they name.
        assert_eq!(
            crate::engine::InstancePolicy::from_component(&component),
            crate::engine::InstancePolicy::Warm {
                pool_size: std::num::NonZeroUsize::new(4).unwrap(),
                max_invocations: std::num::NonZeroUsize::new(100),
                max_concurrency: std::num::NonZeroUsize::new(8).unwrap(),
                reclaim: Some(crate::engine::ReclaimPolicy {
                    window: std::time::Duration::from_secs(30),
                    min_instances: 2,
                }),
            }
        );
    }

    #[test]
    fn try_from_v2_local_resources_parses_allowed_hosts() {
        // Strings flowing in from the proto wire are parsed into typed
        // `AllowedHost` entries. Valid forms should round-trip cleanly.
        let proto = types::v2::LocalResources {
            memory_limit_mb: 0,
            cpu_limit: 0,
            config: Default::default(),
            environment: Default::default(),
            volume_mounts: vec![],
            allowed_hosts: vec![
                "*".to_string(),
                "*.example.com".to_string(),
                "api.example.com:8443".to_string(),
                "https://api.example.com".to_string(),
            ],
            allowed_ip_name_lookups: vec!["*.example.com".to_string(), "127.0.0.1".to_string()],
            allowed_host_loopback_ports: vec![],
        };
        let lr = crate::types::LocalResources::try_from(proto).expect("conversion should succeed");
        assert_eq!(lr.allowed_ip_name_lookups.len(), 2);
        assert!(matches!(
            lr.allowed_ip_name_lookups[0],
            AllowedIpName::SuffixWildcard { .. }
        ));
        assert!(matches!(
            lr.allowed_ip_name_lookups[1],
            AllowedIpName::Ip(_)
        ));
        assert_eq!(lr.allowed_hosts.len(), 4);
        assert!(matches!(lr.allowed_hosts[0], AllowedHost::Any));
        assert!(matches!(
            lr.allowed_hosts[1],
            AllowedHost::SuffixWildcard { .. }
        ));
        assert!(matches!(lr.allowed_hosts[2], AllowedHost::Authority(_)));
        assert!(matches!(lr.allowed_hosts[3], AllowedHost::Url(_)));
    }

    #[test]
    fn try_from_v2_local_resources_rejects_bad_allowed_hosts_entry() {
        // An ambiguous wildcard (`*com` matches every .com) must be
        // rejected — the K8s pattern guards this at admission time, but
        // workloads constructed by other paths land here and the
        // workload start should surface a clear error rather than
        // silently widen egress.
        let proto = types::v2::LocalResources {
            memory_limit_mb: 0,
            cpu_limit: 0,
            config: Default::default(),
            environment: Default::default(),
            volume_mounts: vec![],
            allowed_hosts: vec!["*com".to_string()],
            allowed_ip_name_lookups: vec![],
            allowed_host_loopback_ports: vec![],
        };
        let err = crate::types::LocalResources::try_from(proto)
            .expect_err("conversion should reject ambiguous wildcard");
        let msg = format!("{err:#}");
        assert!(msg.contains("*com"), "{msg}");
        assert!(
            msg.contains("leading dot") || msg.contains("invalid"),
            "{msg}"
        );
    }

    #[test]
    fn try_from_v2_local_resources_collects_all_allowed_hosts_errors() {
        // Three bad entries in one workload — the conversion should report
        // all three in a single error so the user doesn't have to iterate
        // fix → start → fail → fix → start → ... for each entry.
        let proto = types::v2::LocalResources {
            memory_limit_mb: 0,
            cpu_limit: 0,
            config: Default::default(),
            environment: Default::default(),
            volume_mounts: vec![],
            allowed_hosts: vec![
                "*com".to_string(),                       // bare-star wildcard
                "https://api.example.com/v1".to_string(), // has path
                "example.com:notaport".to_string(),       // bad port
            ],
            allowed_ip_name_lookups: vec![],
            allowed_host_loopback_ports: vec![],
        };
        let err = crate::types::LocalResources::try_from(proto)
            .expect_err("conversion should reject all bad entries");
        let msg = format!("{err:#}");
        assert!(msg.contains("*com"), "{msg}");
        assert!(msg.contains("/v1"), "{msg}");
        assert!(msg.contains("notaport"), "{msg}");
    }

    #[tokio::test]
    async fn test_image_pull_secret_to_oci_config_none() {
        let host_config = HostConfig {
            allow_oci_insecure: false,
            ..Default::default()
        };
        let secret: Option<types::v2::ImagePullSecret> = None;
        let config = image_pull_secret_to_oci_config(&host_config, &secret);
        assert!(config.credentials.is_none());
        assert!(!config.insecure);
    }

    #[tokio::test]
    async fn test_image_pull_secret_to_oci_config_basic_auth() {
        let secret = Some(types::v2::ImagePullSecret {
            username: "testuser".to_string(),
            password: "testpass".to_string(),
        });

        let host_config = HostConfig {
            allow_oci_insecure: false,
            ..Default::default()
        };
        let config = image_pull_secret_to_oci_config(&host_config, &secret);
        assert_eq!(
            config.credentials,
            Some(("testuser".to_string(), "testpass".to_string()))
        );
    }
}
