//! HTTP Task Manager API implementation
//!
//! This file contains the implementation of the HTTP Task manager defined in `wit/component.wit`.
//!
//! The top level `world` in the [WIT][wit] for this WebAssembly component looks like the following:
//! ```
//! package wasmcloud:task-manager@0.1.0-draft;
//!
//! world http-task-mangaer {
//!   import wasmcloud:postgres/query@0.1.0-draft;
//!
//!   export tasks;
//!   export wasi:http/incoming-handler@0.2.0;
//! }
//! ```
//!
//! This WebAssembly component:
//!
//! - Uses Postgres for persistence (i.e. the [wasmcloud SQLDB Postgres provider][wasmcloud-postgres-provider])
//! - Exports interfaces for task management
//! - Exports an wasi:http incoming handler so it can be used as a Web server (i.e. by the [wasmCloud HTTP server provider][wasmcloud-http-server-provider])
//!
//! [wit]: <https://github.com/WebAssembly/component-model/blob/main/design/mvp/WIT.md>
//! [wasmcloud-postgres-provider]: <https://github.com/wasmCloud/wasmCloud/tree/main/crates/provider-sqldb-postgres>
//! [wasmcloud-http-server-provider]: <https://github.com/wasmCloud/wasmCloud/tree/main/crates/provider-http-server>

wit_bindgen::generate!({ generate_all });

use anyhow::Result;

// NOTE: the exports below were generated by wit-bindgen
use exports::wasi::http::incoming_handler;
use exports::wasmcloud::task_manager::tasks;
use wasi::http::types::{
    Fields, IncomingRequest, OutgoingBody, OutgoingResponse, ResponseOutparam,
};
//use wasmcloud::postgres::query::query;
//use wasmcloud::postgres::types::TimestampTz;
//use wasmcloud::postgres::types::{PgValue, ResultRow, ResultRowEntry};
use wasmcloud::task_manager::types::{GroupId, Task, TaskId, TaskStatus};

use crate::tasks::{
    GetTaskStatusError, GetTaskStatusesError, GetTasksError, SubmitTaskError, SubmitTasksError,
    UpdateTaskStatusError, UpdateTaskStatusesError,
};
// END wit-bindgen generated imports

/// All implementation of the `component` world hangs off of this struct
struct HttpTaskManager;

// Implementation of wasi:http/incoming-handler
impl incoming_handler::Guest for HttpTaskManager {
    fn handle(_request: IncomingRequest, response_out: ResponseOutparam) {
        let response = OutgoingResponse::new(Fields::new());
        response.set_status_code(200).unwrap();
        let response_body = response.body().unwrap();
        ResponseOutparam::set(response_out, Ok(response));
        response_body
            .write()
            .unwrap()
            .blocking_write_and_flush(b"Hello from Rust!\n")
            .unwrap();
        OutgoingBody::finish(response_body, None).expect("failed to finish response body");
    }
}

// Implementation of our home-grown tasks interface
impl tasks::Guest for HttpTaskManager {
    fn get_tasks_by_group_id(_id: GroupId) -> Result<Vec<Task>, GetTasksError> {
        Err(GetTasksError::Unexpected("not implemented yet".into()))
    }

    fn submit_tasks(
        _id: GroupId,
        _tasks: Vec<Task>,
    ) -> Result<Vec<Result<TaskStatus, SubmitTaskError>>, SubmitTasksError> {
        Err(SubmitTasksError::Unexpected("not implemented yet".into()))
    }

    fn get_task_statuses(
        _ids: Vec<TaskId>,
    ) -> Result<Vec<Result<TaskStatus, GetTaskStatusError>>, GetTaskStatusesError> {
        Err(GetTaskStatusesError::Unexpected(
            "not implemented yet".into(),
        ))
    }

    fn update_task_statuses(
        _updates: Vec<(TaskId, TaskStatus)>,
    ) -> Result<Vec<Result<TaskStatus, UpdateTaskStatusError>>, UpdateTaskStatusesError> {
        Err(UpdateTaskStatusesError::Unexpected(
            "not implemented".into(),
        ))
    }
}

export!(HttpTaskManager);
