package wasmcloud:host-wrpc@1.0.1;

world wrpc-interfaces {
    import wasmcloud:messaging/consumer@0.2.0;
    import wrpc:keyvalue/atomics@0.2.0-draft;
    import wrpc:keyvalue/store@0.2.0-draft;
    import wrpc:keyvalue/batch@0.2.0-draft;
    export wrpc:keyvalue/watcher@0.2.0-draft;

    import wrpc:blobstore/blobstore@0.1.0;

    export wasmcloud:messaging/handler@0.2.0;
}
