name: helm-publish
description: Publish a Helm chart to a registry

inputs:
  chart-name:
    required: true
    description: The name of the chart to publish
  chart-version:
    required: false
    description: The version of the chart to publish
  chart-app-version:
    required: false
    description: The appVersion to set in the chart
  helm-version:
    default: "v3.16.4"
    description: The version of Helm to use
    required: false
  helmfile-version:
    default: "v0.169.2"
    description: The version of Helmfile to use
    required: false
  registry:
    required: true
    description: The registry to publish the chart to
  registry-username:
    required: true
    description: The username to use for the registry
  registry-password:
    required: true
    description: The password to use for the registry
  registry-namespace:
    required: true
    description: The namespace of the chart to publish

runs:
  using: "composite"
  steps:
      - name: Set up Helm
        uses: azure/setup-helm@dda3372f752e03dde6b3237bc9431cdc2f7a02a2 # v5.0.0
        with:
          version: ${{ inputs.helm-version }}

      - name: Login to ${{ inputs.registry }}
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.registry-username }}
          password: ${{ inputs.registry-password }}

      - name: Update dependencies with Helmfile
        uses: helmfile/helmfile-action@02671705b1dda1dc4b0a4ddd4f9f1ea8f4568c6f # v2.4.3
        with:
          helmfile-args: deps
          helmfile-version: ${{ inputs.helmfile-version }}
          helmfile-workdirectory: ${{ format('charts/{0}', inputs.chart-name) }}
          helm-version: ${{ inputs.helm-version }}
          helm-plugins: >
            https://github.com/databus23/helm-diff@v3.1.3

      - name: Package
        if: inputs.chart-app-version != '' && inputs.chart-version != ''
        shell: bash
        env:
          CHART_PATH: ${{ format('charts/{0}', inputs.chart-name)}}
        run: |
          helm package --app-version "${{ inputs.chart-app-version }}" --version "${{ inputs.chart-version }}" ${{ env.CHART_PATH }} -d .helm-charts

      - name: Use Git version
        if: inputs.chart-app-version == '' && inputs.chart-version == ''
        shell: bash
        env:
          CHART_PATH: ${{ format('charts/{0}', inputs.chart-name)}}
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo "VERSION=${VERSION}"
          helm package --app-version "$VERSION" --version "$VERSION" ${{ env.CHART_PATH }} -d .helm-charts

      - name: Publish
        shell: bash
        env:
          CHART_REMOTE: ${{ format('oci://{0}/{1}', inputs.registry, inputs.registry-namespace) }}
        run: |
          for chart in .helm-charts/*; do
            if [ -z "${chart:-}" ]; then
              break
            fi
            helm push "${chart}" "${{ env.CHART_REMOTE }}"
          done
