{
 "title": "Test Environment",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  { "title": "K6", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Iteration Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum(rate(k6_iterations_total[$__rate_interval])) by(test_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Iteration Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, test_id) (rate(k6_iteration_duration_milliseconds_bucket[$__rate_interval])))",
     "legendFormat": "p99 - {{test_id}}"
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "2xx responses",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(k6_http_reqs_total{expected_response=\"true\"}[$__rate_interval])) by(test_id)",
     "legendFormat": "{{test_id}} - success"
    },
    {
     "expr": "sum(rate(k6_http_reqs_total{expected_response=\"false\"}[$__rate_interval])) by(test_id)",
     "legendFormat": "{{test_id}} - failure"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, test_id) (rate(k6_http_req_duration_milliseconds_bucket[$__rate_interval])))",
     "legendFormat": "p99 - {{test_id}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, test_id) (rate(k6_http_req_duration_milliseconds_bucket[$__rate_interval])))",
     "legendFormat": "p95 - {{test_id}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum by(le, test_id) (rate(k6_http_req_duration_milliseconds_bucket[$__rate_interval])))",
     "legendFormat": "p50 - {{test_id}}"
    }
   ]
  },
  {
   "title": "Failures drilldown",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(k6_http_reqs_total{error!=\"\"}[$__rate_interval])) by (test_id,error)",
     "legendFormat": "{{test_id}} - {{error}}"
    }
   ]
  },
  { "title": "Resource Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "CPU usage by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(\nrate(container_cpu_usage_seconds_total{namespace=\"$namespace\", image!=\"\"}[$__rate_interval])\n) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory usage by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", image!=\"\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}