version: 2.0.0

build:
  command: cargo +nightly build --workspace --target wasm32-wasip2 --release
  component_path: target/wasm32-wasip2/release/patch_consumer.wasm

dev:
  wasip3: true
  components:
    - name: patch-producer
      file: target/wasm32-wasip2/release/patch_producer.wasm

new:
  command: cargo fetch
