//! `cargo xtask generate-protos`: generate the Rust bindings for the
//! `wasmcloud.runtime.v2` protobuf service into
//! `crates/wash-runtime/src/washlet/generated/`.
//!
//! The bindings are committed so the published crate builds without
//! `protoc` or the workspace `/proto` directory. Rerun this task after
//! changing `/proto/wasmcloud/runtime/v2`; CI regenerates and fails on
//! any drift between the protos and the committed output.

use std::{
    fs,
    path::{Path, PathBuf},
};

use anyhow::{Context, Result};

pub fn run(workspace: &Path) -> Result<()> {
    let top_proto_dir = workspace.join("proto");
    let proto_dir = top_proto_dir.join("wasmcloud/runtime/v2");
    let generated_dir = workspace.join("crates/wash-runtime/src/washlet/generated");

    let mut proto_files: Vec<PathBuf> = fs::read_dir(&proto_dir)
        .with_context(|| format!("failed to read proto dir {}", proto_dir.display()))?
        .map(|entry| entry.map(|e| e.path()))
        .collect::<Result<_, std::io::Error>>()
        .context("failed to read proto dir entry")?;
    proto_files.retain(|p| p.extension().is_some_and(|ext| ext == "proto"));
    proto_files.sort();

    let tempdir =
        tempfile::tempdir().context("failed to create scratch dir for proto descriptor")?;
    let descriptor_file = tempdir.path().join("runtime.bin");

    fs::create_dir_all(&generated_dir)
        .with_context(|| format!("failed to create {}", generated_dir.display()))?;

    tonic_prost_build::configure()
        .out_dir(&generated_dir)
        .compile_well_known_types(true)
        .file_descriptor_set_path(&descriptor_file)
        .extern_path(".google.protobuf", "::pbjson_types")
        .compile_protos(&proto_files, &[top_proto_dir])
        .context("failed to compile protos")?;

    let descriptor_bytes = fs::read(&descriptor_file).context("failed to read descriptor file")?;

    pbjson_build::Builder::new()
        .out_dir(&generated_dir)
        .register_descriptors(&descriptor_bytes)
        .context("failed to register descriptor")?
        .build(&[".wasmcloud.runtime.v2"])
        .context("failed to build final protos")?;

    let serde_file = generated_dir.join("wasmcloud.runtime.v2.serde.rs");
    let body = fs::read_to_string(&serde_file)
        .with_context(|| format!("failed to read {}", serde_file.display()))?;
    fs::write(
        &serde_file,
        format!("// This file is @generated by pbjson-build.\n{body}"),
    )
    .with_context(|| format!("failed to write {}", serde_file.display()))?;

    println!(
        "generated protobuf bindings into {}",
        generated_dir.display()
    );
    Ok(())
}
