package wasmcloud:runtime@0.1.0;

world http-server {
    import wasi:http/types@0.2.0;
    export wasi:http/incoming-handler@0.2.0;
}

world config {
    import wasi:config/store@0.2.0-rc.1;
}

world logging {
    import wasi:logging/logging@0.1.0-draft;
}

world keyvalue {
    import wasi:keyvalue/atomics@0.2.0-draft;
    import wasi:keyvalue/batch@0.2.0-draft;
    import wasi:keyvalue/store@0.2.0-draft;
}

world blobstore {
    import wasi:blobstore/types@0.2.0-draft;
    import wasi:blobstore/container@0.2.0-draft;
    import wasi:blobstore/blobstore@0.2.0-draft;
}

world messaging {
    import wasmcloud:messaging/types@0.2.0;
    import wasmcloud:messaging/consumer@0.2.0;
    export wasmcloud:messaging/handler@0.2.0;
}

world postgres {
  import wasmcloud:postgres/types@0.1.1-draft;
  import wasmcloud:postgres/query@0.1.1-draft;
  import wasmcloud:postgres/prepared@0.1.1-draft;
}


world otel {
    import wasi:otel/types@0.2.0-rc.1;
    import wasi:otel/tracing@0.2.0-rc.1;
    import wasi:otel/metrics@0.2.0-rc.1;
    import wasi:otel/logs@0.2.0-rc.1;
}
