// Generated by `wit-bindgen-wrpc-go` 0.8.0. DO NOT EDIT!
// provider package contains wRPC bindings for `provider` world
package provider

import (
	exports__wasmcloud__example__system_info "github.com/wasmCloud/wasmCloud/examples/go/providers/custom-template/bindings/exports/wasmcloud/example/system_info"
	wrpc "wrpc.io/go"
)

func Serve(s wrpc.Server, h0 exports__wasmcloud__example__system_info.Handler) (stop func() error, err error) {
	stops := make([]func() error, 0, 1)
	stop = func() error {
		for _, stop := range stops {
			if err := stop(); err != nil {
				return err
			}
		}
		return nil
	}
	stop0, err := exports__wasmcloud__example__system_info.ServeInterface(s, h0)
	if err != nil {
		return
	}
	stops = append(stops, stop0)
	stop = func() error {
		if err := stop0(); err != nil {
			return err
		}
		return nil
	}
	return
}
