package wasmcloud:provider-blobstore-fs;

world interfaces {
    export wrpc:blobstore/blobstore@0.2.0;
}

world extensions {
    export wrpc:extension/manageable@0.0.1;
    export wrpc:extension/configurable@0.0.1;
}
