package wasmcloud:task-manager@0.1.0-draft;

world http-task-manager {
  import wasi:logging/logging@0.1.0-draft;
  import wasmcloud:postgres/query@0.1.1-draft;

  export tasks;
  export wasi:http/incoming-handler@0.2.1;
}
