name: charts
on:
  push:
    branches:
      - "main"
    tags:
      - "v*"
  pull_request:
    paths:
      - "charts/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/setup-go
      - name: Render
        run: make helm-render

  canary:
    if: github.ref == 'refs/heads/main' || contains(github.event.pull_request.labels.*.name, 'canary')
    needs: [test]
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/helm-publish
        with:
          chart-name: runtime-operator
          chart-version: v2-canary
          chart-app-version: canary
          registry: ghcr.io
          registry-username: ${{ github.repository_owner }}
          registry-password: ${{ secrets.GITHUB_TOKEN }}
          registry-namespace: wasmcloud/charts

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [test]
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/helm-publish
        with:
          chart-name: runtime-operator
          registry: ghcr.io
          registry-username: ${{ github.repository_owner }}
          registry-password: ${{ secrets.GITHUB_TOKEN }}
          registry-namespace: wasmcloud/charts