package wasmcloud:test-actors;

/// This world encapsulates a component that:
///
/// - Listens to messages coming in on NATS via the NATS messaging provider
/// - Invokes an Actor component (i.e. an Actor to Actor call)
/// - Invokes an Provider (i.e. an Actor to Provider call)
///
/// The component changes which lattice member (actor/provider) it communicates
/// with depending on the content of the NATS message
///
world messaging-invoker {
  /// Ability to change link names, etc
  import wasmcloud:bus/lattice;

  /// Log messages while we operate
  import wasi:logging/logging;

  /// Invoke wasmcloud:keyvalue contract operations
  import wasmcloud:keyvalue/key-value;

  /// Invoke wasmcloud:keyvalue contract operations
  import wasmcloud:messaging/messaging;

  /// Invoke wasmcloud:blobstore contract operations
  import wasmcloud:blobstore/blobstore;

  /// Invoke wasmcloud:blobstore contract operations
  import wasmcloud:lattice-control/lattice-controller;

  /// Invoke the testing busybox operations
  import test-actors:testing/busybox;

  /// Handle messages coming in via NATS (mediated by the nats-messaging provider)
  export wasmcloud:messaging/message-subscriber;
}
